_: &unix
  name: Unix
  brew:
    - connect
    - coreutils
    - dos2unix
    - ffmpeg
    - findutils
    - gnu-sed
    - jq
    - md5sha1sum
    - p7zip
    - shellcheck
    - telnet
    - tree
    - unrar
    - watch
    - wget
    - youtube-dl
