---
name: Modartt Pianoteq
cask: modartt-pianoteq
file:
  - path: ~/Library/Application Support/Modartt
    state: directory
    mode: '0755'
symlink:
  # Plug-in Presets
  - path: ~/Library/Application Support/Modartt/Pianoteq
    source: ~/Music/Presets & Sounds/Pianoteq
