_: &u_he_hive
  name: u-he Hive
  cask: u-he-hive
  file:
    # License
    - path: ~/Library/Application Support/u-he
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/u-he/com.u-he.Hive.plist
      source: !join_path [*app_license_dir, Music Production/u-he/u-he Hive/com.u-he.Hive.plist]
      mode: '0644'
