_: &reveal_sound_spire
  name: Reveal Sound Spire
  cask: reveal-sound-spire
  file:
    # License
    - path: ~/Library/Application Support/RevealSound
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/RevealSound/spire.lic
      source: !join_path [*app_license_dir, Music Production/Reveal Sound/Reveal Sound Spire/spire.lic]
      mode: '0644'
