_: &spectrasonics_omnisphere
  name: Spectrasonics Omnisphere
  cask: spectrasonics-omnisphere
  file:
    - source: !join_path [*app_license_dir, Music Production/Spectrasonics/Spectrasonics Omnisphere/net.spectrasonics.V6.plist]
      path: ~/Library/Preferences/net.spectrasonics.V6.plist
