_: &synapse_audio_dune
  name: Synapse Audio DUNE
  cask: synapse-audio-dune
  file:
    # License
    - path: /Library/Application Support/Synapse Audio/.DUNE2reg
      source: !join_path [*app_license_dir, Music Production/Synapse Audio/Synapse Audio DUNE/.DUNE2reg]
      sudo: true
