_: &synapse_audio_dune
  name: Synapse Audio DUNE
  cask: synapse-audio-dune
  file:
    - source: !join_path [*app_license_dir, Music Production/Synapse Audio/Synapse Audio DUNE/.DUNE2reg]
      path: /Library/Application Support/Synapse Audio/.DUNE2reg
      sudo: true
