_: &uhe_zebra
  name: u-he Zebra
  cask: u-he-zebra
  file:
    # License
    - path: ~/Library/Application Support/u-he
      state: directory
    - path: ~/Library/Application Support/u-he/com.u-he.Zebra2.plist
      source: !join_path [*app_license_dir, Music Production/u-he/u-he Zebra/com.u-he.Zebra2.plist]
