_: &xfer_records_serum
  name: Xfer Records Serum
  cask:
    - xfer-records-serum
    - xfer-records-serum-update
    - xfer-records-serumfx-update
  file:
    - source: !join_path [*app_license_dir, Music Production/Xfer Records/Xfer Records Serum/user.dat]
      path: ~/Library/Application Support/com.xferrecords.serum/user.dat
