_: &appcleaner
  name: AppCleaner
  cask: appcleaner
  plist:
    - domain: net.freemacsoft.AppCleaner
      values:
        SUEnableAutomaticChecks: true
        SUHasLaunchedBefore: true
        SUSendProfileInfo: false
