_: &appcleaner
  name: AppCleaner
  cask: appcleaner
  plist:
    - domain: net.freemacsoft.AppCleaner
      mode: '0600'
      values:
        # Preferences / Updates / Check updates automatically
        SUEnableAutomaticChecks: true
