_: &bootchamp
  name: BootChamp
  cask: bootchamp
  plist:
    - domain: com.kainjow.BootChamp
      values:
        SUEnableAutomaticChecks: true
        SUHasLaunchedBefore: true
        SUSendProfileInfo: false
  login_item: true
