_: &cog
  name: Cog
  cask: fgimian/general/cog
  plist:
    domain: org.cogx.cog
    mode: '0600'
    values:
      # Check for updates automatically? / Check Automatically
      SUEnableAutomaticChecks: true
