_: &mplayerx
  name: MPlayerX
  cask: mplayerx
  plist:
    - domain: org.niltsh.MPlayerX
      values:
        SUSendProfileInfo: false
        SUEnableAutomaticChecks: true
        # General / Keep window on top / Never
        OnTopMode: 0
