_: &sourcetree
  name: SourceTree
  cask: sourcetree
  file:
    - path: *development_dir
      state: directory
  plist:
    domain: com.torusknot.SourceTreeNotMAS
    mode: '0600'
    values:
      # Atlassian SourceTree / Install / I agree to the Atlassian Customer Agreement.
      agreedToEULA2: true
      # Atlassian SourceTree / Install / Disable 'Help Improve SourceTree by sending data about your usage.'
      analyticsHasAgreed: false
      # Check for updates automatically? / Check Automatically
      SUEnableAutomaticChecks: true
      # Preferences / General / Default user information / Full Name:
      globalUserFullName: Fotis Gimian
      # Preferences / General / Default user information / Email address:
      globalUserEmail: fgimiansoftware@gmail.com
      # Preferences / General / Misc / Project folder
      defaultFolder: *development_dir
      # Preferences / General / Misc / Offer to create bookmarks for newly opened repositories
      createBookmarksOnOpenRepo: false
      # Preferences / Diff / Internal Diff Visualization / Diff view font:
      diffFontName: SourceCodePro-Regular
      diffFontSize: 13.0
      # Workspace / File status / = / Fluid staging
      fileStatusStagingViewMode: 0
      # Workspace / File status / (stage a file) / You staged some changes!
      showStagingTip: false
