_: &transmission
  name: Transmission
  cask: transmission
  plist:
    - domain: org.m0k.transmission
      values:
        # Transfers / Trash original torrent files
        DeleteOriginalTorrent: true
        # Hide the legal disclaimer
        WarningLegal: false
