_: &fish
  name: Fish
  brew: fish
  pip: powerline-status
  file:
    # Fish Profile
    - path: ~/.config
      state: directory
    - path: ~/.config/fish
      state: directory
    - path: ~/.config/fish/config.fish
      source: files/dotfiles/.config/fish/config.fish
