_: &vim
  name: VIM
  vimrc_path: files/dotfiles/.vimrc
  file:
    - path: ~/.vim
      state: directory
    - path: ~/.vim/bundle
      state: directory
  git:
    # Vundle package manager
    - path: ~/.vim/bundle/Vundle.vim
      repo: https://github.com/VundleVim/Vundle.vim.git
