_: &bash
  name: Bash
  brew:
    - bash
    - bash-completion
  pip: powerline-status
  file:
    # Bash Profile
    - path: ~/.bash_profile
      source: files/dotfiles/.bash_profile
    # Bash Profile Bash Completion & Powerline
    - path: ~/.bash_profile.d
      state: directory
    - path: ~/.bash_profile.d/bash_completion.sh
      source: files/dotfiles/.bash_profile.d/bash_completion.sh
    - path: ~/.bash_profile.d/powerline.sh
      source: files/dotfiles/.bash_profile.d/powerline.sh
