_: &dock
  name: Dock

  plist:
    domain: com.apple.dock
    mode: '0600'
    values:
      # Preferences / Size
      tilesize: 60
      # Preferences / Magnification
      magnification: true
      # Make hidden applications translucent in the dock (hidden setting)
      showhidden: true

  # Dock applications (in the left section)
  apps:
    - ForkLift
    - Siri
    - Launchpad
    - Safari
    - Sublime Text
    - Utilities/Terminal
    - Cubase 9.5
    - Audio Hijack
    - XLD
    - Focusrite Control
    - Spotify
    - OpenEmu
    - Messages
    - Skype
    - Slack
    - Textual
    - Clear
    - VMware Fusion
    - App Store
    - System Preferences

  # Dock folders and URLs (in the right section)
  other:
    - path: ~/Downloads
