_: &launchpad
  name: Launchpad

  apps:
    # Page 1: Apple
    -
      # Most Useful Apps
      - Calculator
      - Safari
      - iTunes
      - iBooks
      - App Store
      - System Preferences
      # iWork
      - folder_title: iWork
        folder_layout:
          -
            - Pages
            - Numbers
            - Keynote
      # Apps
      - folder_title: Apps
        folder_layout:
          -
            - Mail
            - Contacts
            - Calendar
            - Reminders
            - Notes
            - Maps
            - Messages
            - FaceTime
            - Photo Booth
            - Photos
            - Preview
            - Dictionary
            - Siri
            - Mission Control
            - Dashboard
      # Other Utilities
      - folder_title: Other
        folder_layout:
          -
            - QuickTime Player
            - TextEdit
            - Grapher
            - DVD Player
            - Time Machine
            - Font Book
            - Chess
            - Stickies
            - Image Capture
            - VoiceOver Utility
            - AirPort Utility
            - Migration Assistant
            - Terminal
            - Activity Monitor
            - Console
            - Keychain Access
            - System Information
            - Automator
            - Script Editor
            - Disk Utility
            - Boot Camp Assistant
            - Digital Color Meter
            - ColorSync Utility
            - Grab
            - Bluetooth File Exchange
            - Audio MIDI Setup
    # Page 2: Desktop Software
    -
      # Proudctivity
      - Affinity Designer
      - Affinity Photo
      - Clear
      - Sublime Text
      - Microsoft Excel
      - Microsoft Word
      - folder_title: Microsoft Office (Other)
        folder_layout:
          -
            - Microsoft OneNote
            - Microsoft Outlook
            - Microsoft PowerPoint
      # General
      - 1Password 6
      - Android File Transfer
      - AppCleaner
      - DaisyDisk
      - Entropy
      - ForkLift
      - World Clock
      # Social
      - Skype
      - Slack
      - Textual
      # Internet
      - Firefox
      - Transmission
      # Games
      - OpenEmu
      # Virtualization
      - VMware Fusion
      # Media Playback & Entertainment
      - Cog
      - Spotify
      - MPlayerX
      - folder_title: Utilities
        folder_layout:
          -
            - BestRes
            - BetterSnapTool
            - Dropbox
            - Flux
            - Gmail Notifier
            - iStat Mini
            - OneDrive
    # Page 3: Audio Software
    -
      # DAWs
      - Cubase 9
      # Tools
      - Audio Hijack
      - Melodyne singletrack
      - XLD
      # Hardware
      - Focusrite Control
      - ReMOTESLEditor
      # Software Managers
      - folder_title: Software Managers
        folder_layout:
          -
            - iLok License Manager
            - eLicenser Control Center
            - Native Access
            - Sonalksis Plugin Manager
      # Native Instruments
      - folder_title: Native Instruments (Other)
        folder_layout:
          -
            - Battery 4
            - Kontakt 5
            - Massive
            - Reaktor 6
            - ServiceCenter

  widgets:
    -
      - Ski Report
      - Calculator
      - Calendar
      - Contacts
      - Dictionary
      - ESPN
      - Flight Tracker
      - Movies
      - Stickies
      - Stocks
      - Tile Game
      - Translation
      - Unit Converter
      - Weather
      - Web Clip
      - World Clock
