_: &safari
  name: Safari
  plist:
    - domain: com.apple.Safari
      values:
        # Bookmarks / Disable 'Show Frequently Visited Sites'
        ShowFrequentlyVisitedSites: false
        # View / Show Status Bar
        ShowStatusBar: true
        # General / Disable 'Open "safe" files after downloading'
        AutoOpenSafeDownloads: false
        # General / File download location / Ask for each download
        AlwaysPromptForDownloadFolder: true
        # AutoFill / Disable 'User names and passwords'
        AutoFillPasswords: false
        # Advanced / Show Develop menu in menu bar
        IncludeDevelopMenu: true
