---
name: Terminal
plist:
  domain: com.apple.Terminal
  mode: '0600'
  values:
    # Preferences / General / Shells open with: Command (complete path):
    Shell: /usr/local/bin/bash

    # Preferences / Profiles / Fots / Default
    Default Window Settings: Fots
    # Preferences / General / On startup open: / New window with profile:
    Startup Window Settings: Fots

    Window Settings:
      Fots:
        # Preferences / Profiles / Add Profile
        name: Fots
        type: Window Settings
        ProfileCurrentVersion: 2.06

        # Preferences / Profiles / Advanced / Bell / Disable 'Audible bell'
        Bell: false

        # Preferences / Profiles / Shell / When the shell exits: / Don't close the window
        shellExitAction: 2

        # Preferences / Profiles / Window / Title / Disable 'Profile name'
        ShowWindowSettingsNameInTitle: false

        # Preferences / Profiles / Window / Window Size
        columnCount: 135
        rowCount: 27

        # Preferences / Profiles / Text / Font
        Font: !macos_font [SourceCodePro-Regular, 16]
        # Preferences / Profiles / Text / Antialias text
        FontAntialias: true
