_: &artsacoustic_reverb
  name: ArtsAcoustic Reverb
  cask: artsacoustic-reverb
  file:
    # License
    - path: ~/Library/Application Support/ArtsAcoustic
      state: directory
    - path: ~/Library/Application Support/ArtsAcoustic/Reverb
      state: directory
    - path: ~/Library/Application Support/ArtsAcoustic/Reverb/Preference.xml
      source: !join_path [*app_license_dir, Music Production/ArtsAcoustic/ArtsAcoustic Reverb/Preference.xml]
