_: &cableguys_volumeshaper
  name: Cableguys VolumeShaper
  cask: cableguys-volumeshaper
  files:
    - source: !join_path [*app_license_dir, Music Production/Cableguys/Cableguys VolumeShaper/de.cableguys.volumeshaper4.plist]
      path: ~/Library/Preferences/de.cableguys.volumeshaper4.plist
