_: &cableguys_filtershaper
  name: Cableguys FilterShaper
  cask: cableguys-filtershaper
  files:
    - source: !join_path [*app_license_dir, Music Production/Cableguys/Cableguys FilterShaper/de.cableguys.filtershaper3.plist]
      path: ~/Library/Preferences/de.cableguys.filtershaper3.plist
