_: &cableguys_volumeshaper
  name: Cableguys VolumeShaper
  cask: cableguys-volumeshaper
  file:
    # License
    - path: ~/Library/Preferences/de.cableguys.volumeshaper4.plist
      source: !join_path [*app_license_dir, Music Production/Cableguys/Cableguys VolumeShaper/de.cableguys.volumeshaper4.plist]
      mode: '0600'
