_: &relab_lx480_complete
  name: Relab LX480 Complete
  cask: relab-lx480-complete
  file:
    # Preferences
    - path: /Library/Application Support/Relab Development/LX480 Complete/Preferences.xml
      source: files/relab_lx480_complete/Preferences.xml
