_: &uhe_mfm2
  name: u-he MFM2
  cask: u-he-mfm2
  files:
    - source: !join_path [*app_license_dir, Music Production/u-he/u-he MFM2/com.u-he.MFM2.plist]
      path: ~/Library/Application Support/u-he/com.u-he.MFM2.plist
