_: &uhe_satin
  name: u-he Satin
  cask: u-he-satin
  file:
    # License
    - path: ~/Library/Application Support/u-he
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/u-he/com.u-he.Satin.plist
      source: !join_path [*app_license_dir, Music Production/u-he/u-he Satin/com.u-he.Satin.plist]
      mode: '0644'
