_: &voxengo_glisseq
  name: Voxengo GlissEQ
  cask:
    - voxengo-glisseq-au-aax
    - voxengo-glisseq-vst-vst3
  file:
    - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo GlissEQ/product-key-name]
      path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/GlissEQ/product-key-name
    - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo GlissEQ/product-key-value]
      path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/GlissEQ/product-key-value
