_: &voxengo_voxformer
  name: Voxengo Voxformer
  cask:
    - voxengo-voxformer-au-aax
    - voxengo-voxformer-vst-vst3
  files:
    - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Voxformer/product-key-name]
      path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Voxformer/product-key-name
    - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Voxformer/product-key-value]
      path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Voxformer/product-key-value
