_: &voxengo_elephant
  name: Voxengo Elephant
  cask:
    - voxengo-elephant-au-aax
    - voxengo-elephant-vst-vst3
  files:
    - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Elephant/product-key-name]
      path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Elephant/product-key-name
    - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Elephant/product-key-value]
      path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Elephant/product-key-value
