_: &unix_general
  name: Unix General
  brew:
    - dos2unix
    - ffmpeg
    - findutils
    - gnu-sed
    - md5sha1sum
    - p7zip
    - shellcheck
    - tree
    - unrar
    - watch
    - wget
    - youtube-dl
