---
name: Sublime Text
cask: sublime-text
pip:
  - python-language-server
  - rope
  - flake8
go:
  - golang.org/x/tools/cmd/goimports
  - github.com/sourcegraph/go-langserver
file:
  - path: ~/Library/Application Support/Sublime Text 3
    state: directory
    mode: '0700'
  - path: ~/Library/Application Support/Sublime Text 3/Installed Packages
    state: directory
    mode: '0700'
  - path: ~/Library/Application Support/Sublime Text 3/Local
    state: directory
    mode: '0700'
  - path: ~/Library/Application Support/Sublime Text 3/Packages
    state: directory
    mode: '0700'
  - path: ~/Library/Application Support/Sublime Text 3/Packages/User
    state: directory
    mode: '0700'
  - path: ~/Library/Application Support/Sublime Text 3/Packages/Go
    state: directory
    mode: '0755'

  # Sublime Text License
  - path: ~/Library/Application Support/Sublime Text 3/Local/License.sublime_license
    source: !join_path [*app_license_dir, General/Sublime Text/License.sublime_license]
    mode: '0644'

  # Bash Profile Default Editor
  - path: ~/.bash_profile.d/sublime_text.sh
    source: files/dotfiles/.bash_profile.d/sublime_text.sh

rsync:
  # Preferences
  - path: ~/Library/Application Support/Sublime Text 3/Packages/User
    source: files/sublime_text/User/
  - path: ~/Library/Application Support/Sublime Text 3/Packages/Go
    source: files/sublime_text/Go/

download:
  # Package Control
  - path: ~/Library/Application Support/Sublime Text 3/Installed Packages
    url: http://packagecontrol.io/Package Control.sublime-package
    mode: '0644'

# User Preferences
json:
  - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
    mode: '0644'
    values:
      # Monokai Extended color scheme
      color_scheme: Packages/Color Scheme - Default/Monokai.sublime-color-scheme

      # Soda Theme
      theme: Soda Dark 3.sublime-theme

      # Automatically search in selection when multiple lines are selected
      auto_find_in_selection: true

      # Wrap autocomplete suggestions
      auto_complete_cycle: true

      # Ensure that auto-completion is triggered on period for Python and Go
      auto_complete_triggers:
        - {selector: text.html, characters: <}
        - {selector: source.go, characters: .}
        - {selector: source.python, characters: .}

      # Set a ruler at 100 characters to ensure we catch long lines
      rulers: [100]

      # Appearance Settings
      always_show_minimap_viewport: true
      fade_fold_buttons: false
      font_face: Source Code Pro
      highlight_line: true
      line_padding_top: 1
      line_padding_bottom: 1
      scroll_speed: 0

      # File Formatting Settings
      default_line_ending: unix
      ensure_newline_at_eof_on_save: true
      translate_tabs_to_spaces: true
      trim_trailing_white_space_on_save: true

      # Spell Checking
      spell_check: true
      dictionary: Packages/Language - English/en_GB.dic

      # Editing Settings
      shift_tab_unindent: true

      # Ensure that files are opened in a tab instead of a new window
      open_files_in_new_window: false

      # Directories to ignore (added the Python 3 cache directory to the list)
      folder_exclude_patterns: [.svn, .git, .hg, CVS, __pycache__]

      # Packages to keep disabled
      ignored_packages: [Markdown, Vintage]

  # Package Control Packages
  - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
    mode: '0644'
    values:
      installed_packages:
        # Autocompletes symbols using all open files
        - All Autocomplete
        # Conversion between snake case and camel case
        - Case Conversion
        # Go formatting on save
        - Gofmt
        # INI syntax support
        - INI
        # Language Server Protocol support
        - LSP
        # Markdown themes and syntax highlighting
        - MarkdownEditing
        # The package manager for Sublime Text
        - Package Control
        # Better title case implementation
        - Smart Title Case
        # Built in Terminal
        - Terminus
        # The wonderful Soda theme
        - Theme - Soda

handler:
  - public.plain-text
