_: &1password
  name: 1Password
  cask: 1password
  file:
    # License
    - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits
      state: directory
    - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License
      state: directory
    - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License/License.onepassword-license
      source: !join_path [*app_license_dir, General/1Password/License.onepassword-license]
  plist:
    - domain: com.agilebits.onepassword4
      values:
        WelcomeWindowShown: true
        LockOnMainAppExit: false
        LockOnIdle: true
        ShowRichIcons: true
        KeepHelperRunning: true
        UserMetricsSkippedNewsletterSignupKey: true
        CompletedEssentialSettings: true
    - domain: 2BUA8C4S2C.com.agilebits.onepassword4-helper
      values:
        autosave: false
