_: &affinity_designer
  name: Affinity Designer
  appstore: Affinity Designer
  plist:
    - domain: com.seriflabs.affinitydesigner
      container: com.seriflabs.affinitydesigner
      values:
        com.seriflabs.ShowWelcomeScreen: false
