_: &affinity_photo
  appstore: Affinity Photo
  defaults:
    - domain: com.seriflabs.affinityphoto
      container: com.seriflabs.affinityphoto
      values:
        com.seriflabs.ShowWelcomeScreen: false
