_: &affinity_designer
  name: Affinity Designer
  appstore: Affinity Designer
  file:
    - path: ~/Library/Containers/com.seriflabs.affinitydesigner
      state: directory
    - path: ~/Library/Containers/com.seriflabs.affinitydesigner/Data
      state: directory
    - path: ~/Library/Containers/com.seriflabs.affinitydesigner/Data/Library
      state: directory
    - path: ~/Library/Containers/com.seriflabs.affinitydesigner/Data/Library/Preferences
      state: directory
  plist:
    - domain: com.seriflabs.affinitydesigner
      container: com.seriflabs.affinitydesigner
      values:
        com.seriflabs.ShowWelcomeScreen: false
