_: &affinity_designer
  appstore: Affinity Designer
  defaults:
    - domain: com.seriflabs.affinitydesigner
      container: com.seriflabs.affinitydesigner
      values:
        com.seriflabs.ShowWelcomeScreen: false
