_: &affinity_photo
  name: Affinity Photo
  appstore: Affinity Photo
  plist:
    - domain: com.seriflabs.affinityphoto
      container: com.seriflabs.affinityphoto
      values:
        com.seriflabs.ShowWelcomeScreen: false
