_: &audio_hijack
  name: Audio Hijack
  cask: audio-hijack
  plist:
    - domain: com.rogueamoeba.audiohijack3
      values:
        homeWindowShown: true
  symlink:
    - source: !join_path [*app_config_dir, Audio Hijack]
      path: '~/Library/Application Support/Audio Hijack'
