_: &daisydisk
  name: DaisyDisk
  cask: daisydisk
  plist:
    - domain: com.daisydiskapp.DaisyDiskStandAlone
      values:
        moveToApplicationsFolderAlertSuppress: true
  file:
    - source: !join_path [*app_license_dir, General/DaisyDisk/License.DaisyDisk]
      path: ~/Library/Application Support/DaisyDisk/License.DaisyDisk
