_: &dash
  name: Dash
  cask: dash
  plist:
    - domain: com.kapeli.dashdoc
      values:
        moveToApplicationsFolderAlertSuppress: true
        didSuppressDownloadDocsetsAlert: true
        DHNotificationNoDocsetsFound: true
        reorderDocsetsAlertSuppressed: true
        DHNotificationDocsetPressEnterOrClickIconTip: true
        noDocsetsFoundAlertSuppressed: true
        syncFolderPath: !join_path [*app_config_dir, Dash]
        snippetSQLPath: !join_path [*app_config_dir, Dash/library.dash]
        # Note that the following setting is required or Dash thinks it needs
        # to set everything up again
        migratedV2Prefs: true
  file:
    - source: !join_path [*app_license_dir, General/Dash/license.dash-license]
      path: ~/Library/Application Support/Dash/License/license.dash-license
