_: &entropy
  name: Entropy
  cask: entropy
  file:
    # License
    - path: ~/Library/Application Support/.els-A4AD28617A455C07768787313A53E2F79D9FA258
      source: !join_path [*app_license_dir, General/Entropy/.els-A4AD28617A455C07768787313A53E2F79D9FA258]
  plist:
    - domain: com.eigenlogik.Entropy
      values:
        moveToApplicationsFolderAlertSuppress: true
        SUEnableAutomaticChecks: true
        SUSendProfileInfo: false
        # Extraction / Auto-extract on open
        AutoExtractOnOpen: true
  handler:
    - public.zip-archive
    - public.tar-archive
    - org.gnu.gnu-zip-tar-archive
    - public.tar-bzip2-archive
    - org.gnu.gnu-zip-archive
    - public.bzip2-archive
    - public.cpio-archive
