_: &entropy
  name: Entropy
  cask: entropy
  file:
    # License
    - path: ~/Library/Application Support/.els-A4AD28617A455C07768787313A53E2F79D9FA258
      source: !join_path [*app_license_dir, General/Entropy/.els-A4AD28617A455C07768787313A53E2F79D9FA258]
      mode: '0644'
  plist:
    - domain: com.eigenlogik.Entropy
      mode: '0600'
      values:
        # Preferences / Updates / Automatically check for updates
        SUEnableAutomaticChecks: true
        # Preferences / Extraction / Auto-extract on open
        AutoExtractOnOpen: true
  handler:
    # Preferences / File Types / Zip Archive
    - public.zip-archive
    # Preferences / File Types / Tarball
    - public.tar-archive
    # Preferences / File Types / Tar + gz
    - org.gnu.gnu-zip-tar-archive
    # Preferences / File Types / Tar + bz2
    - public.tar-bzip2-archive
    # Preferences / File Types / Gzip
    - org.gnu.gnu-zip-archive
    # Preferences / File Types / BZip2 Archive
    - public.bzip2-archive
    # Preferences / File Types / CPIO Archive
    - public.cpio-archive
