_: &focus
  name: Focus
  cask: focus
  file:
    # License
    - path: ~/.491062.padl
      source: !join_path [*app_license_dir, General/Focus/.491062.padl]
      mode: '0644'
    - path: ~/Library/Application Support/Focus
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/Focus/paddata.padl
      source: !join_path [*app_license_dir, General/Focus/paddata.padl]
      mode: '0644'
