_: &forklift
  name: Forklift
  cask: forklift-beta
  plist:
    - domain: com.binarynights.ForkLift-3
      values:
        SetupDone: true
        SUEnableAutomaticChecks: true
        SUHasLaunchedBefore: true
        SUSendProfileInfo: false
        # Preferences / General / Enable dark mode
        DarkMode: true
        # Preferences / General / Untick Enable Forklift mini in the menubar
        ForkLiftMiniEnabled: false
        # View / Show Titlebar
        ShowTitlebar: true
