_: &microsoft_office
  name: Microsoft Office
  cask: microsoft-office
  file:
    - path: ~/Library/Group Containers/UBF8T346G9.Office
      state: directory
    - path: ~/Library/Containers/com.microsoft.Excel
      state: directory
    - path: ~/Library/Containers/com.microsoft.Excel/Data
      state: directory
    - path: ~/Library/Containers/com.microsoft.Excel/Data/Library
      state: directory
    - path: ~/Library/Containers/com.microsoft.Excel/Data/Library/Preferences
      state: directory
    - path: ~/Library/Containers/com.microsoft.Word
      state: directory
    - path: ~/Library/Containers/com.microsoft.Word/Data
      state: directory
    - path: ~/Library/Containers/com.microsoft.Word/Data/Library
      state: directory
    - path: ~/Library/Containers/com.microsoft.Word/Data/Library/Preferences
      state: directory
    - path: ~/Library/Containers/com.microsoft.Powerpoint
      state: directory
    - path: ~/Library/Containers/com.microsoft.Powerpoint/Data
      state: directory
    - path: ~/Library/Containers/com.microsoft.Powerpoint/Data/Library
      state: directory
    - path: ~/Library/Containers/com.microsoft.Powerpoint/Data/Library/Preferences
      state: directory
    - path: ~/Library/Containers/com.microsoft.onenote.mac
      state: directory
    - path: ~/Library/Containers/com.microsoft.onenote.mac/Data
      state: directory
    - path: ~/Library/Containers/com.microsoft.onenote.mac/Data/Library
      state: directory
    - path: ~/Library/Containers/com.microsoft.onenote.mac/Data/Library/Preferences
      state: directory
    - path: ~/Library/Containers/com.microsoft.Outlook
      state: directory
    - path: ~/Library/Containers/com.microsoft.Outlook/Data
      state: directory
    - path: ~/Library/Containers/com.microsoft.Outlook/Data/Library
      state: directory
    - path: ~/Library/Containers/com.microsoft.Outlook/Data/Library/Preferences
      state: directory
  plist:
    - path: ~/Library/Group Containers/UBF8T346G9.Office/com.microsoft.officeprefs.plist
      values:
        kCUIThemePreferencesThemeKeyPath: 0
    - domain: com.microsoft.Excel
      container: com.microsoft.Excel
      values:
        kSubUIAppCompletedFirstRunSetup1507: true
    - domain: com.microsoft.Word
      container: com.microsoft.Word
      values:
        kSubUIAppCompletedFirstRunSetup1507: true
    - domain: com.microsoft.Powerpoint
      container: com.microsoft.Powerpoint
      values:
        kSubUIAppCompletedFirstRunSetup1507: true
    - domain: com.microsoft.onenote.mac
      container: com.microsoft.onenote.mac
      values:
        kSubUIAppCompletedFirstRunSetup1507: true
    - domain: com.microsoft.Outlook
      container: com.microsoft.Outlook
      values:
        kSubUIAppCompletedFirstRunSetup1507: true
