_: &sublime_text
  name: Sublime Text
  cask: sublime-text
  handler:
    - public.plain-text

  file:
    - path: ~/Library/Application Support/Sublime Text 3/Installed Packages
      state: directory
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User
      state: directory
    - path: ~/Library/Application Support/Sublime Text 3/Local/License.sublime_license
      source: !join_path [*app_license_dir, General/Sublime Text/License.sublime_license]
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Doxy.sublime-license
      source: !join_path [*app_license_dir, General/Sublime Text/Doxy.sublime-license]
    - path: ~/.bash_profile.d/sublime_text.sh
      source: files/dotfiles/.bash_profile.d/sublime_text.sh

  download:
    - path: ~/Library/Application Support/Sublime Text 3/Installed Packages
      url: http://packagecontrol.io/Package Control.sublime-package

  rsync:
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User
      source: files/sublime_text/

  # Specify our main user preferences for Sublime Text
  json:
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
      values:
        # Monokai Extended color scheme
        color_scheme: !first_existing_path
          base_dir: ~/Library/Application Support/Sublime Text 3
          paths:
            - Packages/Monokai Extended/Monokai Extended.tmTheme
            - Packages/User/SublimeLinter/Monokai Extended (SL).tmTheme

        # Soda Theme
        theme: Soda Dark 3.sublime-theme

        # Automatically search in selection when multiple lines are selected
        auto_find_in_selection: true

        # Auto-trigger Angular.js controller completions within the ng-controller
        auto_complete_triggers:
          - characters: ng-controller="*
            selector: punctuation.definition.string

        # Set a ruler at 99 characters to ensure we catch long lines
        rulers: [99]

        # Appearance Settings
        always_show_minimap_viewport: true
        fade_fold_buttons: false
        font_face: Source Code Pro
        highlight_line: true
        highlight_modified_tabs: true
        line_padding_top: 1
        line_padding_bottom: 1
        scroll_past_end: false
        scroll_speed: 0
        word_wrap: false

        # File Formatting Settings
        default_line_ending: unix
        ensure_newline_at_eof_on_save: true
        tab_size: 2
        translate_tabs_to_spaces: true
        trim_trailing_white_space_on_save: true
        enable_hexadecimal_encoding: false

        # Editing Settings
        dictionary: Packages/Language - English/en_GB.dic
        shift_tab_unindent: true
        spell_check: true

        # Ensure that files are opened in a tab instead of a new window
        open_files_in_new_window: false

        # Directories to ignore (added the Python 3 cache directory to the list)
        folder_exclude_patterns: [.svn, .git, .hg, CVS, __pycache__]

        # Packages to keep disabled
        ignored_packages: [Markdown, Vintage]

    # Specify a list of packages to install via Package Control
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
      values:
        installed_packages:
          # Use ctrl+alt+n to easily create a new file
          - AdvancedNewFile
          # Ability to easily align definitions (handy with Puppet code)
          - Alignment
          # Autocompletes symbols using all open files
          - All Autocomplete
          # Angular.js snippets & syntax support
          - AngularJS
          # Support for Ansible YAML files
          - Ansible
          # CoffeeScript syntax support
          - Better CoffeeScript
          # Support for binary plist files and syntax
          - BinaryPlist
          # Clearly highlights matching brackets tags .etc
          - BracketHighlighter
          # Color picker useful for CSS
          - ColorPicker
          # Distraction free mode without entering full-screen
          - DistractionFreeWindow
          # Dockerfile syntax support
          - Dockerfile Syntax Highlighting
          # Auto-generated comment blocks
          - DoxyDoxygen
          # Emmet HTML code generation
          - Emmet
          # .gitconfig syntax support
          - Git Config
          # Jade syntax support
          - Jade
          # Additional JavaScript snippets
          - JavaScript & NodeJS Snippets
          # Jinja2 syntax support
          - Jinja2
          # LESS syntax support
          - LESS
          # Live browser reloading for web development and Markdown
          - LiveReload
          # Ability to preview rendered Markdown code
          - Markdown Preview
          # Markdown themes and syntax highlighting
          - MarkdownEditing
          # An improved Soda-flavoured Monokai theme with Markdown support
          - Monokai Extended
          # The package manager for Sublime Text
          - Package Control
          # A system for managing task lists in Sublime Text
          - PlainTasks
          # Puppet syntax support
          - Puppet
          # SASS and SCSS syntax support
          - Sass
          # Better title case implementation
          - Smart Title Case
          # The main sublime linter core
          - SublimeLinter
          # Linting of CSS using CSS Lint
          - SublimeLinter-csslint
          # Linting of Python using flake8
          - SublimeLinter-flake8
          # Linting of JavaScript using JSHint
          - SublimeLinter-jshint
          # Linting of JSON using the built-in JSON parser
          - SublimeLinter-json
          # Linting of YAML using PyYAML
          - SublimeLinter-pyyaml
          # Linting of Bash scripts using shellcheck
          - SublimeLinter-shellcheck
          # Terraform syntax support
          - Terraform
          # The wonderful Soda theme
          - Theme - Soda
          # Typewriter mode for centered scrolling in Markdown files
          - Typewriter
