_: &textual
  name: Textual
  cask: textual
  file:
    # License
    - path: ~/Library/Application Support/Textual
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/Textual/Textual_User_License_v2.plist
      source: !join_path [*app_license_dir, General/Textual/Textual_User_License_v2.plist]
      mode: '0644'
  plist:
    domain: com.codeux.apps.textual
    mode: '0600'
    values:
      # Preferences / General / Updates: / Just notify if there are updates
      SUEnableAutomaticChecks: true
      SUAutomaticallyUpdate: false
      # Preferences / Style / Theme / Style: / Sapientia
      'Theme -> Name': 'resource:Sapientia'
      # Preferences / Style / Theme / Style: / Sapientia / Preferred Selection / Do not show this message again
      'Text Input Prompt Suppression -> theme_override_info': true
      World Controller Client Configurations:
        -
          # Server / Server Properties... / Basic Settings / Channel List
          channelList:
            - channelName: '#ansible'
              notifications: {}
              uniqueIdentifier: E098773D-3D12-4A74-A41E-AB10BFF8F3C6
            - channelName: '#chef'
              notifications: {}
              uniqueIdentifier: D1147EB5-800E-4964-AA0F-A1A46AE605DE
            - channelName: '#puppet'
              notifications: {}
              uniqueIdentifier: 53A803F9-AC92-4451-9F76-0EB295D86AC2
            - channelName: '#salt'
              notifications: {}
              uniqueIdentifier: 882298B8-3A7D-4C85-A6D0-F84B2495A7BB
            - channelName: '#python'
              notifications: {}
              uniqueIdentifier: 3EEE5D4F-5F9F-4662-9B5C-72E32D1B9FBF
            - channelName: '#terraform'
              notifications: {}
              uniqueIdentifier: 3ADD3253-F023-4CAA-B3E1-C8823F89251F
          # Server / Server Properties... / Basic Settings / General / Connection Name:
          connectionName: freenode
          # Server / Server Properties... / Basic Settings / General / Server Address:
          serverAddress: chat.freenode.net
          # Server / Server Properties... / Basic Settings / General / Connect when Textual opens
          autoConnect: True
          # Server / Server Properties... / Basic Settings / Identity / Nickname:
          nickname: fgimian
          # Server / Server Properties... / Basic Settings / Identity / Username:
          username: fgimian
          # Server / Server Properties... / Basic Settings / Identity / Real name:
          realName: Fotis Gimian
