_: &vmware_fusion
  name: VMware Fusion
  cask: vmware-fusion
  file:
    # License
    - path: /Library/Preferences/VMware Fusion
      state: directory
      owner: root
      group: wheel
      mode: '0755'
      sudo: true
    - path: /Library/Preferences/VMware Fusion/license-fusion-80-e1-201505
      source: !join_path [*app_license_dir, General/VMware Fusion/license-fusion-80-e1-201505]
      owner: root
      group: wheel
      mode: '0644'
      sudo: true
    # Preferences
    - path: ~/Library/Preferences/VMware Fusion
      state: directory
      mode: '0755'
    - path: ~/Library/Preferences/VMware Fusion/preferences
      source: files/vmware_fusion/preferences
      mode: '0600'
  plist:
    - domain: com.vmware.fusion
      mode: '0600'
      values:
        # Virtual Machine Library / View / Show items as icons
        PLInventoryWindowStylePref: 1
        # Preferences / General / Show in menu bar / Only when Fusion is running
        showStartMenu3: 2
