_: &vmware_fusion
  name: VMware Fusion
  cask: vmware-fusion
  plist:
    - domain: com.vmware.fusion
      values:
        # Virtual Machine Library / View / Show items as icons
        PLInventoryWindowStylePref: 1
        # Preferences / General / Show in menu bar / Only when Fusion is running
        showStartMenu3: 2
  file:
    - source: files/vmware_fusion/preferences
      path: ~/Library/Preferences/VMware Fusion/preferences
    - source: !join_path [*app_license_dir, General/VMware Fusion/license-fusion-80-e1-201505]
      path: /Library/Preferences/VMware Fusion/license-fusion-80-e1-201505
      sudo: true
