---
name: Ableton Live 10 Suite
cask: ableton-live-10-suite
file:
  # License
  - path: ~/Library/Application Support/Ableton
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/Ableton/Live 10.0.3
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/Ableton/Live 10.0.3/Unlock
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/Ableton/Live 10.0.3/Unlock/Unlock.cfg
    source: !join_path [*app_license_dir, Music Production/Ableton/Ableton Live 10 Suite/Unlock.cfg]
    mode: '0644'
