---
name: Ableton Live 10 Suite
cask: ableton-live-10-suite
file:
  # License
  - path: ~/Library/Application Support/Ableton
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/Ableton/Live 10.0.5
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/Ableton/Live 10.0.5/Unlock
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/Ableton/Live 10.0.5/Unlock/Unlock.cfg
    source: !join_path [*app_license_dir, Music Production/Ableton/Ableton Live 10 Suite/Unlock.cfg]
    mode: '0644'
  # Skin
  - path: /Applications/Ableton Live 10 Suite.app/Contents/App-Resources/Themes/05Fots.ask
    source: files/ableton_live/05Fots.ask
    mode: '0644'
