---
name: Apple Logic Pro X
appstore: Logic Pro X
plist:
  domain: com.apple.logic10
  mode: '0600'
  values:
    # Preferences / General / Startup Action / Ask
    startupAction: 6
    # Preferences / General / Advanced / Show Advanced Tools
    userLevel: 10
    # Preferences / General / Advanced / Additional Options / Audio
    FeatureAvailable_ExpertAudio: true
    # Preferences / General / Advanced / Additional Options / Surround
    FeatureAvailable_Surround: true
    # Preferences / General / Advanced / Additional Options / MIDI
    FeatureAvailable_ExpertMIDI: true
    # Preferences / General / Advanced / Additional Options / Control Surfaces
    FeatureAvailable_ExpertCS: true
    # Preferences / General / Advanced / Additional Options / Score
    FeatureAvailable_ExpertScore: true
    # Preferences / General / Advanced / Additional Options / Advanced Editing
    FeatureAvailable_ExpertEditing: true
    # Track / New Tracks... / Details
    NewTrackSheetDefaults:
      ShowDetails: true
