_: &python
  name: Python
  brew:
    - python3
    - pip-completion
  pip:
    - setuptools
    - pip
    - ipython
    - flake8
    - powerline-status
  file:
    # Preferences
    - path: ~/.ipython
      state: directory
    - path: ~/.ipython/profile_default
      state: directory
    - path: ~/.ipython/profile_default/ipython_config.py
      source: files/dotfiles/.ipython/profile_default/ipython_config.py
