_: &ruby
  name: Ruby
  brew:
    - rbenv
    - ruby-build
    - ruby-completion
    - rake-completion
  file:
    # Bash Profile rbenv Activation
    - path: ~/.bash_profile.d/rbenv.sh
      source: files/dotfiles/.bash_profile.d/rbenv.sh
