---
name: 1Password
cask: 1password
file:
  # License
  - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits
    state: directory
    mode: '0700'
  - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License
    state: directory
    mode: '0755'
  - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License/1Password 7 License.onepassword7-license-mac
    source: !join_path [*app_license_dir, General/1Password/1Password 7 License.onepassword7-license-mac]
    mode: '0644'

  - path: ~/Library/Containers/com.agilebits.onepassword7
    state: directory
    mode: '0700'
  - path: ~/Library/Containers/com.agilebits.onepassword7/Data
    state: directory
    mode: '0700'
  - path: ~/Library/Containers/com.agilebits.onepassword7/Data/Library
    state: directory
    mode: '0700'
  - path: ~/Library/Containers/com.agilebits.onepassword7/Data/Library/Preferences
    state: directory
    mode: '0700'
plist:
  - domain: com.agilebits.onepassword7
    container: com.agilebits.onepassword7
    mode: '0600'
    values:
      # Preferences / Browsers / Disable 'Detect new usernames and passwords and ofer to save them'
      autosave: false
