---
name: 1Password
cask: 1password6
file:
  # License
  - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits
    state: directory
    mode: '0755'
  - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License
    state: directory
    mode: '0755'
  - path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License/License.onepassword-license
    source: !join_path [*app_license_dir, General/1Password/License.onepassword-license]
    mode: '0644'
plist:
  - domain: com.agilebits.onepassword4
    mode: '0600'
    values:
      # Initial setup completed and newsletter signup skipped
      CompletedEssentialSettings: true
      UserMetricsSkippedNewsletterSignupKey: true
      # Preferences / General / Always keep 1Password mini running
      KeepHelperRunning: true
      # Preferences / General / Use rich icons
      ShowRichIcons: true
      # Preferences / Security / Disable 'Lock when main window is closed'
      LockOnMainAppExit: false
      # Preferences / Security / Lock after computer is idle for 5 minutes
      LockOnIdle: true

  - domain: 2BUA8C4S2C.com.agilebits.onepassword4-helper
    mode: '0600'
    values:
      # Preferences / Browsers / Disable 'Detect new usernames and passwords and ofer to save them'
      autosave: false
