_: &daisydisk
  name: DaisyDisk
  cask: daisydisk
  file:
    # License
    - path: ~/Library/Application Support/DaisyDisk
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/DaisyDisk/License.DaisyDisk
      source: !join_path [*app_license_dir, General/DaisyDisk/License.DaisyDisk]
      mode: '0644'
