---
name: Flux
cask: flux
plist:
  domain: org.herf.Flux
  mode: '0600'
  values:
    # Daytime
    dayColorTemp: 5000.0
    # Sunset
    nightColorTemp: 4400.0
    # Bedtime
    lateColorTemp: 3400.0
    # Location
    locationTextField: Melbourne, Australia
    locationType: L
    location: '-37.814107,144.963280'
    # 6:00 AM is when I wake up
    wakeTime: 360
login_item: true
