_: &skype
  name: Skype
  cask: skype
  plist:
    domain: com.skype.skype
    mode: '0600'
    values:
      # Preferences / Contacts / Disable 'Show Mac Contacts'
      ShowAddressBookContacts: false
      # View / as List
      ContactListViewMode: 1
