_: &sublime_text
  name: Sublime Text
  cask: sublime-text
  file:
    - path: ~/Library/Application Support/Sublime Text 3
      state: directory
      mode: '0700'
    - path: ~/Library/Application Support/Sublime Text 3/Installed Packages
      state: directory
      mode: '0700'
    - path: ~/Library/Application Support/Sublime Text 3/Packages
      state: directory
      mode: '0700'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/Python
      state: directory
      mode: '0700'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User
      state: directory
      mode: '0700'

    # Sublime Text License
    - path: ~/Library/Application Support/Sublime Text 3/Local
      state: directory
      mode: '0700'
    - path: ~/Library/Application Support/Sublime Text 3/Local/License.sublime_license
      source: !join_path [*app_license_dir, General/Sublime Text/License.sublime_license]
      mode: '0644'
    # Doxy License
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Doxy.sublime-license
      source: !join_path [*app_license_dir, General/Sublime Text/Doxy.sublime-license]
      mode: '0644'

    # Preferences
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Anaconda.sublime-settings
      source: files/sublime_text/Anaconda.sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap
      source: files/sublime_text/Default (OSX).sublime-keymap
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Doxy.sublime-settings
      source: files/sublime_text/Doxy.sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Markdown (Standard).sublime-settings
      source: files/sublime_text/Markdown (Standard).sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Markdown.sublime-settings
      source: files/sublime_text/Markdown.sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/MultiMarkdown.sublime-settings
      source: files/sublime_text/MultiMarkdown.sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Python.sublime-settings
      source: files/sublime_text/Python.sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Soda Dark 3.sublime-theme
      source: files/sublime_text/Soda Dark 3.sublime-theme
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings
      source: files/sublime_text/SublimeLinter.sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/bh_core.sublime-settings
      source: files/sublime_text/bh_core.sublime-settings
      mode: '0644'
    - path: ~/Library/Application Support/Sublime Text 3/Packages/Python/Completion Rules.tmPreferences
      source: files/sublime_text/Completion Rules.tmPreferences
      mode: '0644'

    # Bash Profile Default Editor
    - path: ~/.bash_profile.d/sublime_text.sh
      source: files/dotfiles/.bash_profile.d/sublime_text.sh
  pip: PyYAML
  download:
    # Package Control
    - path: ~/Library/Application Support/Sublime Text 3/Installed Packages
      url: http://packagecontrol.io/Package Control.sublime-package
      mode: '0644'

  # User Preferences
  json:
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
      mode: '0644'
      values:
        # Monokai Extended color scheme
        color_scheme: Packages/Monokai Extended/Monokai Extended.tmTheme

        # Soda Theme
        theme: Soda Dark 3.sublime-theme

        # Automatically search in selection when multiple lines are selected
        auto_find_in_selection: true

        # Set a ruler at 99 characters to ensure we catch long lines
        rulers: [99]

        # Appearance Settings
        always_show_minimap_viewport: true
        fade_fold_buttons: false
        font_face: Source Code Pro
        highlight_line: true
        highlight_modified_tabs: true
        line_padding_top: 1
        line_padding_bottom: 1
        scroll_past_end: false
        scroll_speed: 0
        word_wrap: false

        # File Formatting Settings
        default_line_ending: unix
        ensure_newline_at_eof_on_save: true
        tab_size: 2
        translate_tabs_to_spaces: true
        trim_trailing_white_space_on_save: true
        enable_hexadecimal_encoding: false

        # Editing Settings
        dictionary: Packages/Language - English/en_GB.dic
        shift_tab_unindent: true
        spell_check: true

        # Ensure that files are opened in a tab instead of a new window
        open_files_in_new_window: false

        # Directories to ignore (added the Python 3 cache directory to the list)
        folder_exclude_patterns: [.svn, .git, .hg, CVS, __pycache__]

        # Packages to keep disabled
        ignored_packages: [Markdown, Vintage]

    # Package Control Packages
    - path: ~/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
      mode: '0644'
      values:
        # Use curl for downloads to work around https://github.com/20Tauri/DoxyDoxygen/issues/103
        downloader_precedence:
          osx: [curl, urllib]

        installed_packages:
          # Autocompletes symbols using all open files
          - All Autocomplete
          # Python autocomplete and IDE features
          - Anaconda
          # Support for Ansible YAML files
          - Ansible
          # Clearly highlights matching brackets tags .etc
          - BracketHighlighter
          # Makes URLs clickable
          - Clickable URLs
          # Crystal syntax support
          - Crystal
          # Dockerfile syntax support
          - Dockerfile Syntax Highlighting
          # Auto-generated comment blocks
          - DoxyDoxygen
          # .gitconfig syntax support
          - Git Config
          # INI syntax support
          - INI
          # Jinja2 syntax support
          - Jinja2
          # Provides a way to re-indent JSON data
          - JSON Reindent
          # Markdown themes and syntax highlighting
          - MarkdownEditing
          # An improved Soda-flavoured Monokai theme with Markdown support
          - Monokai Extended
          # The package manager for Sublime Text
          - Package Control
          # Spec syntax support
          - RPM Spec Syntax
          # Better title case implementation
          - Smart Title Case
          # The main sublime linter core
          - SublimeLinter
          # Linting of Python using flake8
          - SublimeLinter-flake8
          # Linting of JSON using the built-in JSON parser
          - SublimeLinter-json
          # Linting of YAML using PyYAML
          - SublimeLinter-contrib-yamllint
          # Linting of Bash scripts using shellcheck
          - SublimeLinter-shellcheck
          # Terraform syntax support
          - Terraform
          # The wonderful Soda theme
          - Theme - Soda
          # Typewriter mode for centered scrolling in Markdown files
          - Typewriter

  handler:
    - public.plain-text
