_: &dmgaudio_equilibrium
  name: DMG Audio EQuilibrium
  cask: dmgaudio-equilibrium
  file:
    - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio EQuilibrium/license]
      path: ~/Library/Application Support/DMGAudio/EQuilibrium/license
