_: &dmgaudio_trackgate
  name: DMG Audio TrackGate
  cask: dmgaudio-trackgate
  file:
    # License
    - path: ~/Library/Application Support/DMGAudio
      state: directory
    - path: ~/Library/Application Support/DMGAudio/TrackGate
      state: directory
    - path: ~/Library/Application Support/DMGAudio/TrackGate/license
      source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackGate/license]
