_: &dmgaudio_limitless
  name: DMG Audio Limitless
  cask: dmgaudio-limitless
  file:
    - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Limitless/license]
      path: ~/Library/Application Support/DMGAudio/Limitless/license
