_: &dmgaudio_dualism
  name: DMG Audio Dualism
  cask: dmgaudio-dualism
  file:
    # License
    - path: ~/Library/Application Support/DMGAudio
      state: directory
    - path: ~/Library/Application Support/DMGAudio/Dualism
      state: directory
    - path: ~/Library/Application Support/DMGAudio/Dualism/license
      source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Dualism/license]
