_: &dmgaudio_dualism
  name: DMG Audio Dualism
  cask: dmgaudio-dualism
  files:
    - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Dualism/license]
      path: ~/Library/Application Support/DMGAudio/Dualism/license
