_: &dmgaudio_essence
  name: DMG Audio Essence
  cask: dmgaudio-essence
  file:
    - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Essence/license]
      path: ~/Library/Application Support/DMGAudio/Essence/license
