_: &dmgaudio_trackgate
  name: DMG Audio TrackGate
  cask: dmgaudio-trackgate
  files:
    - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackGate/license]
      path: ~/Library/Application Support/DMGAudio/TrackGate/license
