_: &dmgaudio_compassion
  name: DMG Audio Compassion
  cask: dmgaudio-compassion
  file:
    - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Compassion/license]
      path: ~/Library/Application Support/DMGAudio/Compassion/license
