_: &dmgaudio_trackds
  name: DMG Audio TrackDS
  cask: dmgaudio-trackds
  files:
    - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackDS/license]
      path: ~/Library/Application Support/DMGAudio/TrackDS/license
