_: &cableguys_shaperbox
  name: Cableguys ShaperBox
  cask: cableguys-shaperbox
  file:
    # License
    - path: ~/Library/Preferences/de.cableguys.shaperbox.plist
      source: !join_path [*app_license_dir, Music Production/Cableguys/Cableguys ShaperBox/de.cableguys.shaperbox.plist]
      mode: '0600'
