---
name: DMG Audio TrackComp
cask: dmgaudio-trackcomp
file:
  # License
  - path: ~/Library/Application Support/DMGAudio
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/DMGAudio/TrackComp
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/DMGAudio/TrackComp/license
    source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackComp/license]
    mode: '0644'
