_: &dmgaudio_trackds
  name: DMG Audio TrackDS
  cask: dmgaudio-trackds
  file:
    # License
    - path: ~/Library/Application Support/DMGAudio
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/DMGAudio/TrackDS
      state: directory
      mode: '0755'
    - path: ~/Library/Application Support/DMGAudio/TrackDS/license
      source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackDS/license]
      mode: '0644'
