---
name: DMG Audio EQuality
cask: dmgaudio-equality
file:
  # License
  - path: ~/Library/Application Support/DMGAudio
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/DMGAudio/EQuality
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/DMGAudio/EQuality/license
    source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio EQuality/license]
    mode: '0644'
