---
name: u-he MFM2
cask: u-he-mfm2
file:
  # License
  - path: ~/Library/Application Support/u-he
    state: directory
    mode: '0755'
  - path: ~/Library/Application Support/u-he/com.u-he.MFM2.plist
    source: !join_path [*app_license_dir, Music Production/u-he/u-he MFM2/com.u-he.MFM2.plist]
    mode: '0644'
