---
name: Voxengo Elephant
cask:
  - voxengo-elephant-au-aax
  - voxengo-elephant-vst-vst3
file:
  # License
  - path: ~/Library/Preferences/Voxengo
    state: directory
    mode: '0755'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins
    state: directory
    mode: '0755'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Elephant
    state: directory
    mode: '0755'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Elephant/product-key-name
    source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Elephant/product-key-name]
    mode: '0644'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Elephant/product-key-value
    source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Elephant/product-key-value]
    mode: '0644'
