---
name: Voxengo Voxformer
cask:
  - voxengo-voxformer-au-aax
  - voxengo-voxformer-vst-vst3
file:
  # License
  - path: ~/Library/Preferences/Voxengo
    state: directory
    mode: '0755'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins
    state: directory
    mode: '0755'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Voxformer
    state: directory
    mode: '0755'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Voxformer/product-key-name
    source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Voxformer/product-key-name]
    mode: '0644'
  - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Voxformer/product-key-value
    source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Voxformer/product-key-value]
    mode: '0644'
