_: &voxengo_deft_compressor
  name: Voxengo Deft Compressor
  cask:
    - voxengo-deft-compressor-au-aax
    - voxengo-deft-compressor-vst-vst3
  file:
    # License
    - path: ~/Library/Preferences/Voxengo
      state: directory
      mode: '0755'
    - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins
      state: directory
      mode: '0755'
    - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Deft Compressor
      state: directory
      mode: '0755'
    - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Deft Compressor/product-key-name
      source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Deft Compressor/product-key-name]
      mode: '0644'
    - path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Deft Compressor/product-key-value
      source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Deft Compressor/product-key-value]
      mode: '0644'
