default_apps_associations:
  # Sublime text
  Sublime Text:
    - public.plain-text

  # Entropy
  Entropy:
    - public.zip-archive
    - public.tar-archive
    - org.gnu.gnu-zip-tar-archive
    - public.tar-bzip2-archive
    - org.gnu.gnu-zip-archive
    - public.bzip2-archive
    - public.cpio-archive
