favourites_layout:
  # Special
  - All My Files

  # Cloud Storage
  - iCloud Drive
  - ~/Dropbox
  - ~/OneDrive

  # Apps
  - /Applications

  # Home
  - '~'
  - ~/Desktop
  - ~/Documents
  - ~/Downloads
  - ~/Movies
  - ~/Pictures
  - ~/Music
