---
# Set license root directory
app_license_dir: &app_license_dir '~/Google Drive/self/Software Licenses'

# Sample library and music production software source locations
sample_library_source: !first_existing_dir
  - /Volumes/Backup Mac 1/Software/Sample Libraries
  - /Volumes/Backup Mac 2/Software/Sample Libraries
  - /Volumes/Software Archive/Sample Libraries
music_software_source: !first_existing_dir
  - /Volumes/Backup Mac 1/Software/Music Production
  - /Volumes/Backup Mac 2/Software/Music Production
  - /Volumes/Software Archive/Music Production
