# Set our development directory
development_dir: &development_dir '~/Documents/Development'

# Set license root directory
app_license_dir: &app_license_dir '~/Documents/Software Licenses'

# Sample library and music production software source locations
sample_library_sources:
  - /Volumes/Backup Mac 1/Software/Sample Libraries
  - /Volumes/Backup Mac 2/Software/Sample Libraries
  - /Volumes/Software Archive/Sample Libraries
music_software_sources:
  - /Volumes/Backup Mac 1/Software/Music Production
  - /Volumes/Backup Mac 2/Software/Music Production
  - /Volumes/Software Archive/Music Production
