# Destination path to install all sample libraries to
sample_library_dir: /Volumes/Sample Libraries

# Komplete sample libraries to install
komplete_libraries:
  # Battery Factory Library
  - Battery 4 Factory Library

  # Kontakt Factory Library
  - Kontakt Factory Library

  # Synthesizers
  # - Retro Machines Mk2

  # Acoustic Pianos
  - Alicias Keys
  - The Gentleman
  - The Giant
  - The Grandeur
  - The Maverick
  - Una Corda

  # Drums and Percussion
  # - Abbey Road 50s Drummer
  # - Abbey Road 60s Drummer
  # - Abbey Road 70s Drummer
  # - Abbey Road 80s Drummer
  # - Abbey Road Modern Drummer
  # - Abbey Road Vintage Drummer
  # - Drum Lab
  # - Maschine Drum Selection
  # - Studio Drummer

  # World Instruments
  # - Balinese Gamelan
  # - Cuba
  - India
  # - West Africa

  # Organs and Electric Pianos
  # - George Duke Soul Treasures
  - Scarbee Vintage Keys
  # - Vintage Organs

  # Acoustic and Electric Guitars
  # - Scarbee Funk Guitarist
  # - Session Guitarist - Strummed Acoustic

  # Electric Bass
  # - Scarbee Jay-Bass
  # - Scarbee MM-Bass
  # - Scarbee MM-Bass Amped
  # - Scarbee Pre-Bass
  # - Scarbee Pre-Bass Amped
  # - Scarbee Rickenbacker Bass

  # Classical Instruments
  - Session Horns Pro
  - Session Strings Pro
  # - Symphony Essentials Brass Ensemble
  # - Symphony Essentials Brass Solo
  # - Symphony Essentials String Ensemble
  # - Symphony Essentials Woodwind Ensemble
  # - Symphony Essentials Woodwind Solo

  # Cinematic
  - Action Strikes
  # - Action Strings
  - Damage
  # - Emotive Strings
  - Evolve Mutations
  - Evolve Mutations 2
  - Evolve R2
  - Kinetic Metal
  - Rise and Hit

# The sample libraries to install and their properties
sample_libraries:
  # Blakus
  # - Blakus pocketBlakus

  # Cinematic Studio Series
  - Cinematic Studio Piano
  - Cinematic Studio Strings

  # Heavyocity
  - name: Heavyocity Gravity Pack 02 Vocalise
    base_dir: GP02 Vocalise
  - name: Heavyocity Gravity Pack 04 Vocalise 2
    base_dir: GP04 Vocalise 2

  # Ivy Audio
  - name: Ivy Audio Clare Solo
    base_dir: Ivy Audio - Clare Solo v2
  - name: Ivy Audio Piano in 162
    base_dir: Ivy Audio - Piano in 162

  # Orchestral Tools (Berlin Series Core)
  - name: Orchestral Tools Berlin Brass
    installer: BBR Mac Installer.pkg
  - name: Orchestral Tools Berlin Percussion
    installer: BPC Mac Installer.pkg
  - name: Orchestral Tools Berlin Strings
    installer: BST Mac Installer.pkg
  - name: Orchestral Tools Berlin Woodwinds
    installer: BWW Mac Installer.pkg

  # Orchestral Tools (Berlin Series Expansions)
  - Orchestral Tools Berlin Brass Expansion C (SFX French Horns)
  - Orchestral Tools Berlin Percussion Expansion A (Timpani)
  - Orchestral Tools Berlin Strings Expansion A (Special Bows I)
  - Orchestral Tools Berlin Strings Expansion B (Special Bows II)
  - Orchestral Tools Berlin Strings Expansion D (First Chairs)
  - Orchestral Tools Berlin Strings Expansion E (SFX)
  - Orchestral Tools Berlin Woodwinds Expansion A (Additional Instruments)
  - Orchestral Tools Berlin Woodwinds Expansion B (Soloists I)
  - Orchestral Tools Berlin Woodwinds Expansion C (Soloists II)
  - Orchestral Tools Berlin Woodwinds Expansion D (SFX)

  # Orchestral Tools Metropolis Ark
  - name: Orchestral Tools Metropolis Ark 1 (The Monumental Orchestra)
    installer: METROPOLIS ARK I Mac Installer.pkg
  - name: Orchestral Tools Metropolis Ark 2 (Orchestra of the Deep)
    installer: METROPOLIS Ark 2 Mac Installer.pkg

  # Orchestral Tools Soloists Series
  - Orchestral Tools Nocturne Cello (Soloists II)
  - Orchestral Tools Nocturne Violin (Soloists I)

  # Orchestral Tools Tools Collection
  # - Orchestral Tools Orchestral String Runs
  - Orchestral Tools Symphonic Sphere

  # Orchestral Tools The Series
  # - name: Orchestral Tools The Orchestral Grands
  #   extract_subdirs:
  #     tog_instruments_v1.3.zip: Instruments/v1.3

  # Soundiron
  - name: Soundiron Mars Symphonic Mens Choir
    base_dir: Soundiron_Mars_Mens_Choir
  - name: Soundiron Venus Symphonic Womens Choir
    base_dir: Soundiron_Venus_Womens_Choir

  # Spitfire Audio
  - Spitfire Albion ONE library
  - Spitfire Harp library
  - Spitfire HZ01 library
  - Spitfire Loegria library

  # Zero-G
  - name: Zero-G ETHERA Cinematic Vocal Instrument
    base_dir: Zero-G_ETHERA_1.1_Update
    extract_subdirs:
      ETHERA_ROLI_PATCHES.zip: Ethera Instruments/Extra Sounds

  # Focusrite
  # - name: Focusrite 2016 Loopmasters Content
  #   base_dir: Focusrite 2GB Loopmasters Content

  # Freshly Squeezed Samples
  - Freshly Squeezed Samples Dave Parkinson Trance Essentials
  - name: Freshly Squeezed Samples Sean Tyas Kick Essentials Volume 1
    base_dir: Sean Tyas - Kick Essentials Volume 1

  # Vengeance
  - Vengeance Effects Vol 1
  - Vengeance Effects Vol 2
  - Vengeance Electro Essentials Vol 1
  - Vengeance Essential Clubsounds Vol 1
  - Vengeance Essential Clubsounds Vol 2
  - Vengeance Essential Clubsounds Vol 3

  # Wave Alchemy
  - name: Wave Alchemy Drum Machine Collection
    base_dir: wa_drum_machine_collection
  - name: Wave Alchemy Drum Tools 01 Deluxe
    base_dir: wa_drum_tools_01_deluxe
  - name: Wave Alchemy Drum Tools 02
    base_dir: wa_drum_tools_02
  - name: Wave Alchemy Wired Electronics
    base_dir: wave_alchemy_wired_electronics

  # Vocals
  - Sonic Element Vocal Trance Recordings
