---
globals: !include globals.yaml
macos_system: !include software/macos/system.yaml

software:
  Homebrew:
    - !include software/taps.yaml

  Essential Unix:
    !include
    path: software/unix_tooling
    extension: yaml
    files:
      - bash
      - python

  Essential Desktop Software:
    !include
    path: software/desktop_software
    extension: yaml
    files:
      - sublime_text
      - spotify

  macOS:
    !include
    path: software/macos
    extension: yaml
    files:
      - general
      - dock
      - finder
      - safari
      - terminal

  Unix:
    !include
    path: software/unix_tooling
    extension: yaml
    files:
      - unix
      - git
      - hugo
      - rar
      - ruby

  Desktop Software / Freeware:
    !include
    path: software/desktop_software
    extension: yaml
    files:
      - adblock
      - cog
      - dropbox
      - flux
      - gmail_notifier
      - iina
      - openemu
      - osxfuse
      - otp_auth
      - skype
      - transmission
      - waterfox
      - xld

  Desktop Software / Commercial:
    !include
    path: software/desktop_software
    extension: yaml
    files:
      - 1password
      - affinity_designer
      - affinity_photo
      - audio_hijack
      - bettersnaptool
      - daisydisk
      - entropy
      - forklift
      - handyprint
      - istat_mini
      - iwork
      - microsoft_office
      - textual
      - things
      - vmware_fusion

  Music Production Software / DAWs, Tools & Drivers:
    !include
    path: software/production_software
    extension: yaml
    files:
      - ableton_live_10_suite
      # - celemony_melodyne_editor
      - elicenser_control_center
      - focusrite_control
      - ilok_license_manager
      - native_instruments_native_access
      - novation_remote_sl_template_editor
      - musescore
      - ocenaudio
      - steinberg_elicenser_control_center
      - steinberg_cubase_pro_9v5

  Music Production Software / Plug-ins (Effect):
    !include
    path: software/production_plugin_effects
    extension: yaml
    files:
      # ArtsAcoustic
      - artsacoustic_reverb

      # Audeze
      - audeze_reveal

      # Audio Damage
      # - audio_damage_eos

      # Cableguys
      # - cableguys_filtershaper
      - cableguys_shaperbox
      - cableguys_volumeshaper

      # Cytomic
      - cytomic_the_drop
      - cytomic_the_glue

      # Dada Life
      # - dada_life_sausage_fattener

      # DMG Audio
      # - dmgaudio_compassion
      - dmgaudio_dualism
      # - dmgaudio_equality
      # - dmgaudio_equick
      - dmgaudio_equilibrium
      - dmgaudio_essence
      - dmgaudio_expurgate
      - dmgaudio_limitless
      # - dmgaudio_pitchfunk
      - dmgaudio_trackcomp
      - dmgaudio_trackcontrol
      - dmgaudio_trackds
      - dmgaudio_trackgate
      - dmgaudio_tracklimit
      - dmgaudio_trackmeter

      # Eventide
      # - eventide_2016_stereo_room

      # Exponential Audio
      - exponential_audio_r2_stereo_reverb

      # Focusrite
      # - focusrite_red_plugin_suite

      # Goodhertz
      # - goodhertz_canopener_studio

      # Illformed
      # BUGGY: Illformed Glitch crashes frequently when being inserted in Cubase
      # - illformed_glitch

      # Klanghelm
      - klanghelm_vumt

      # Native Instruments
      # - native_instruments_driver
      # - native_instruments_guitar_rig_5
      - native_instruments_phasis
      # - native_instruments_premium_tube_series
      - native_instruments_replika_xt
      # - native_instruments_reverb_classics
      # - native_instruments_solid_mix_series
      - native_instruments_supercharger_gt
      - native_instruments_transient_master
      - native_instruments_vintage_compressors

      # Relab
      - relab_lx480_complete

      # Softube
      # - softube_amp_room_essentials
      # - softube_drawmer_s73
      # - softube_fet_compressor
      # - softube_fix_flanger_and_doubler
      # - softube_saturation_knob
      # - softube_tsar_1r
      # - softube_tube_delay

      # Sonalksis
      - sonalksis_plugin_manager
      - sonalksis_creative_elements
      # - sonalksis_essentials
      # - sonalksis_freeg
      # - sonalksis_mastering_suite
      # - sonalksis_multiband_dynamics

      # Soundtoys
      # BUGGY: Soundtoys plugins crash randomly when being inserted in Cubase
      # - soundtoys_echoboy_jr
      # - soundtoys_little_plate
      # - soundtoys_sie_q

      # u-he
      # BUGGY: u-he plugins crash Cubase randomly due to a bug with the preset browser
      - u_he_mfm2
      # - u_he_satin
      - u_he_uhbik

      # ValhallaDSP
      # - valhalladsp_valhallaspacemodulator
      # BUGGY: ValhallaVintageVerb crashes Cubase randomly when using multiple instances and popups
      # - valhalladsp_valhallavintageverb

      # Voxengo
      # - voxengo_deft_compressor
      - voxengo_elephant
      # - voxengo_glisseq
      # - voxengo_msed
      # - voxengo_span
      # - voxengo_voxformer

  # Music Production Software / Plug-ins (Guitar Rig Effects):
  #   !include
  #   path: software/production_plugin_effects/native_instruments_guitar_rig_5
  #   extension: yaml
  #   files:
  #     - native_instruments_rammfire
  #     - native_instruments_reflektor
  #     - native_instruments_traktors_12

  Music Production Software / Plug-ins (Instrument):
    !include
    path: software/production_plugin_instruments
    extension: yaml
    files:
      # LennarDigital
      - lennardigital_sylenth1

      # Modartt
      - modartt_pianoteq

      # Native Instruments
      # - native_instruments_absynth_5
      - native_instruments_battery_4
      # - native_instruments_fm8
      # - native_instruments_komplete_kontrol
      - native_instruments_kontakt_5
      - native_instruments_massive
      # - native_instruments_reaktor_6

      # Reveal Sound
      - reveal_sound_spire

      # Spectrasonics
      - spectrasonics_omnisphere

      # Steinberg
      # - steinberg_padshop
      # - steinberg_retrologue

      # Synapse Audio
      - synapse_audio_dune

      # u-he
      # BUGGY: u-he plugins crash Cubase randomly due to a bug with the preset browser
      - u_he_hive
      - u_he_zebra

      # Xfer Records
      - xfer_records_serum

  # Music Production Software / Plug-ins (Reaktor Instruments):
  #   !include
  #   path: software/production_plugin_instruments/native_instruments_reaktor_instruments
  #   extension: yaml
  #   files:
  #     - native_instruments_flesh
  #     - native_instruments_form
  #     - native_instruments_kontour
  #     - native_instruments_monark
  #     - native_instruments_polyplex
  #     - native_instruments_razor
  #     - native_instruments_reaktor_prism
  #     - native_instruments_reaktor_spark
  #     - native_instruments_rounds
  #     - native_instruments_skanner_xt

  # Music Production Software / Plug-ins (Reaktor Effects):
  #   !include
  #   path: software/production_plugin_effects/native_instruments_reaktor_effects
  #   extension: yaml
  #   files:
  #     - native_instruments_molekular
  #     - native_instruments_the_finger
  #     - native_instruments_the_mouth

dock_layout: !include software/dock_layout.yaml
launchpad_layout: !include software/launchpad_layout.yaml
