software:
  Essentials:
    - *taps
    - *bash
    - *python
    - *fonts
    - *sublime_text
    - *spotify
    - *terminal

  macOS:
    - *macos_general
    - *finder
    - *safari

  Unix:
    - *unix_general
    - *git
    - *hugo
    - *ruby

  Desktop Software / Freeware:
    - *android_file_transfer
    - *appcleaner
    - *bestres
    - *cog
    - *dropbox
    - *firefox
    - *flux
    - *gmail_notifier
    - *mplayerx
    - *onedrive
    - *openemu
    - *osxfuse
    - *skype
    - *slack
    - *transmission
    - *xld

  Desktop Software / Commercial:
    - *1password
    - *affinity_designer
    - *affinity_photo
    - *audio_hijack
    - *bettersnaptool
    - *clear
    - *daisydisk
    - *entropy
    - *forklift
    - *istat_mini
    - *iwork
    - *microsoft_office
    - *textual
    - *vmware_fusion
    - *world_clock

  Music Production Software / DAWs, Tools & Drivers:
    - *celemony_melodyne_editor
    - *elicenser_control_center
    - *focusrite_control
    - *native_instruments_native_access
    - *novation_remote_sl_template_editor
    - *steinberg_cubase_pro_9

  Music Production Software / Plug-ins (Effect):
    - *artsacoustic_reverb
    - *audio_damage_eos
    - *cableguys_filtershaper
    - *cableguys_volumeshaper
    - *cytomic_the_drop
    - *cytomic_the_glue
    - *dmgaudio_dualism
    - *dmgaudio_equilibrium
    - *dmgaudio_essence
    - *dmgaudio_expurgate
    - *dmgaudio_limitless
    - *dmgaudio_trackcontrol
    - *dmgaudio_trackds
    - *dmgaudio_trackgate
    - *dmgaudio_tracklimit
    - *dmgaudio_trackmeter
    - *focusrite_red_plugin_suite
    - *illformed_glitch
    - *native_instruments_premium_tube_series
    - *native_instruments_replika_xt
    - *native_instruments_reverb_classics
    - *native_instruments_solid_mix_series
    - *native_instruments_supercharger_gt
    - *native_instruments_transient_master
    - *native_instruments_vintage_compressors
    - *relab_lx480_complete
    - *softube_fet_compressor
    - *softube_fix_flanger_and_doubler
    - *softube_saturation_knob
    - *softube_tsar_1r
    - *sonalksis_plugin_manager
    - *sonalksis_creative_elements
    - *sonalksis_essentials
    - *soundtoys_5
    - *uhe_mfm2
    - *uhe_satin
    - *uhe_uhbik
    - *valhalladsp_valhallaspacemodulator
    - *valhalladsp_valhallavintageverb

  Music Production Software / Plug-ins (Instrument):
    - *lennardigital_sylenth1
    - *native_instruments_battery_4
    - *native_instruments_kontakt_5
    - *native_instruments_massive
    - *native_instruments_reaktor_6
    - *reveal_sound_spire
    - *spectrasonics_omnisphere
    - *synapse_audio_dune
    - *uhe_hive
    - *uhe_zebra
    - *xfer_records_serum

  Music Production Software / Reaktor Instruments:
    - *native_instruments_form
    - *native_instruments_monark
    - *native_instruments_polyplex
    - *native_instruments_razor

  macOS Dock & Launchpad:
    - *dock
    - *launchpad
