software:
  Essentials:
    - *taps
    - *bash
    - *python
    - *fonts
    - *sublime_text
    - *spotify
    - *terminal

  macOS:
    - *macos_general
    - *finder
    - *safari

  Unix:
    - *unix_general
    - *git
    - *hugo
    - *ruby

  Desktop Software / Freeware:
    - *cog
    - *dropbox
    - *waterfox
    - *flux
    - *gmail_notifier
    - *mplayerx
    - *onedrive
    - *openemu
    - *osxfuse
    - *otp_auth
    - *skype
    - *slack
    - *transmission
    - *whatsapp
    - *xld

  Desktop Software / Commercial:
    - *1password
    - *affinity_designer
    - *affinity_photo
    - *audio_hijack
    - *bettersnaptool
    - *clear
    - *daisydisk
    - *entropy
    - *forklift
    - *handyprint
    - *istat_mini
    - *iwork
    - *microsoft_office
    - *textual
    - *vmware_fusion

  Music Production Software / DAWs, Tools & Drivers:
    # - *ableton_live_9_suite
    # - *celemony_melodyne_editor
    - *elicenser_control_center
    - *focusrite_control
    - *ilok_license_manager
    - *native_instruments_native_access
    - *novation_remote_sl_template_editor
    - *musescore
    - *ocenaudio
    - *steinberg_cubase_pro_9v5
    - *touchosc_editor

  Music Production Software / Plug-ins (Effect):
    # ArtsAcoustic
    - *artsacoustic_reverb

    # Audeze
    - *audeze_reveal

    # Audio Damage
    # - *audio_damage_eos

    # Cableguys
    # - *cableguys_filtershaper
    - *cableguys_shaperbox
    - *cableguys_volumeshaper

    # Cytomic
    - *cytomic_the_drop
    - *cytomic_the_glue

    # Dada Life
    # - *dada_life_sausage_fattener

    # DMG Audio
    # - *dmgaudio_compassion
    - *dmgaudio_dualism
    # - *dmgaudio_equality
    # - *dmgaudio_equick
    - *dmgaudio_equilibrium
    - *dmgaudio_essence
    - *dmgaudio_expurgate
    - *dmgaudio_limitless
    # - *dmgaudio_pitchfunk
    - *dmgaudio_trackcomp
    - *dmgaudio_trackcontrol
    - *dmgaudio_trackds
    - *dmgaudio_trackgate
    - *dmgaudio_tracklimit
    - *dmgaudio_trackmeter

    # Eventide
    # - *eventide_2016_stereo_room

    # Exponential Audio
    - *exponential_audio_r2_stereo_reverb

    # Focusrite
    # - *focusrite_red_plugin_suite

    # Goodhertz
    # - *goodhertz_canopener_studio

    # Illformed
    # BUGGY: Illformed Glitch crashes frequently when being inserted in Cubase
    # - *illformed_glitch

    # Klanghelm
    - *klanghelm_vumt

    # Native Instruments
    # - *native_instruments_driver
    - *native_instruments_phasis
    # - *native_instruments_premium_tube_series
    - *native_instruments_replika_xt
    # - *native_instruments_reverb_classics
    # - *native_instruments_solid_mix_series
    - *native_instruments_supercharger_gt
    - *native_instruments_transient_master
    - *native_instruments_vintage_compressors

    # Relab
    - *relab_lx480_complete

    # Softube
    # - *softube_amp_room_essentials
    # - *softube_drawmer_s73
    # - *softube_fet_compressor
    # - *softube_fix_flanger_and_doubler
    # - *softube_saturation_knob
    # - *softube_tsar_1r
    # - *softube_tube_delay

    # Sonalksis
    - *sonalksis_plugin_manager
    - *sonalksis_creative_elements
    # - *sonalksis_essentials
    # - *sonalksis_freeg
    # - *sonalksis_mastering_suite
    # - *sonalksis_multiband_dynamics

    # Soundtoys
    # BUGGY: Soundtoys plugins crash randomly when being inserted in Cubase
    # - *soundtoys_echoboy_jr
    # - *soundtoys_little_plate
    # - *soundtoys_sie_q

    # u-he
    # BUGGY: u-he plugins crash Cubase randomly due to a bug with the preset browser
    # - *u_he_mfm2
    # - *u_he_satin
    # - *u_he_uhbik

    # ValhallaDSP
    # - *valhalladsp_valhallaspacemodulator
    # BUGGY: ValhallaVintageVerb crashes Cubase randomly when using multiple instances and popups
    # - *valhalladsp_valhallavintageverb

    # Voxengo
    # - *voxengo_deft_compressor
    - *voxengo_elephant
    # - *voxengo_glisseq
    # - *voxengo_msed
    # - *voxengo_span
    # - *voxengo_voxformer

  # Music Production Software / Plug-ins (Guitar Rig Effects):
  #   - *native_instruments_guitar_rig_5
  #   - *native_instruments_rammfire
  #   - *native_instruments_reflektor
  #   - *native_instruments_traktors_12

  Music Production Software / Plug-ins (Instrument):
    # LennarDigital
    - *lennardigital_sylenth1

    # Modartt
    - *modartt_pianoteq

    # Native Instruments
    # - *native_instruments_absynth_5
    - *native_instruments_battery_4
    # - *native_instruments_fm8
    # - *native_instruments_komplete_kontrol
    - *native_instruments_kontakt_5
    - *native_instruments_massive

    # Reveal Sound
    - *reveal_sound_spire

    # Spectrasonics
    - *spectrasonics_omnisphere

    # Steinberg
    # - *steinberg_padshop
    # - *steinberg_retrologue

    # Synapse Audio
    - *synapse_audio_dune

    # u-he
    # BUGGY: u-he plugins crash Cubase randomly due to a bug with the preset browser
    # - *u_he_hive
    # - *u_he_zebra

    # Xfer Records
    - *xfer_records_serum

  # Music Production Software / Plug-ins (Reaktor Instruments & Effects):
  #   - *native_instruments_reaktor_6
  #   # Reaktor Effects
  #   - *native_instruments_molekular
  #   - *native_instruments_the_finger
  #   - *native_instruments_the_mouth
  #   # Reaktor Instruments
  #   - *native_instruments_flesh
  #   - *native_instruments_form
  #   - *native_instruments_kontour
  #   - *native_instruments_monark
  #   - *native_instruments_polyplex
  #   - *native_instruments_razor
  #   - *native_instruments_reaktor_prism
  #   - *native_instruments_reaktor_spark
  #   - *native_instruments_rounds
  #   - *native_instruments_skanner_xt

  macOS Dock & Launchpad:
    - *dock
    - *launchpad
