---
globals: !include globals.yaml
macos_system: !include software/macos_system.yaml

software:
  Essentials:
    - !include software/taps.yaml
    - !include software/unix_tooling/bash.yaml
    - !include software/unix_tooling/crystal.yaml
    - !include software/unix_tooling/python.yaml
    - !include software/fonts.yaml
    - !include software/desktop_software/sublime_text.yaml
    - !include software/desktop_software/spotify.yaml
    - !include software/desktop_software/terminal.yaml

  macOS:
    - !include software/macos_general.yaml
    - !include software/desktop_software/dock.yaml
    - !include software/desktop_software/finder.yaml
    - !include software/desktop_software/safari.yaml

  Unix:
    - !include software/unix_tooling/unix.yaml
    - !include software/unix_tooling/git.yaml
    - !include software/unix_tooling/hugo.yaml
    - !include software/unix_tooling/ruby.yaml

  Desktop Software / Freeware:
    - !include software/desktop_software/cog.yaml
    - !include software/desktop_software/dropbox.yaml
    - !include software/desktop_software/flux.yaml
    - !include software/desktop_software/gmail_notifier.yaml
    - !include software/desktop_software/mplayerx.yaml
    - !include software/desktop_software/openemu.yaml
    - !include software/desktop_software/osxfuse.yaml
    - !include software/desktop_software/otp_auth.yaml
    - !include software/desktop_software/skype.yaml
    - !include software/desktop_software/transmission.yaml
    - !include software/desktop_software/waterfox.yaml
    - !include software/desktop_software/xld.yaml

  Desktop Software / Commercial:
    - !include software/desktop_software/1password.yaml
    - !include software/desktop_software/affinity_designer.yaml
    - !include software/desktop_software/affinity_photo.yaml
    - !include software/desktop_software/audio_hijack.yaml
    - !include software/desktop_software/bettersnaptool.yaml
    - !include software/desktop_software/daisydisk.yaml
    - !include software/desktop_software/entropy.yaml
    - !include software/desktop_software/forklift.yaml
    - !include software/desktop_software/handyprint.yaml
    - !include software/desktop_software/istat_mini.yaml
    - !include software/desktop_software/iwork.yaml
    - !include software/desktop_software/microsoft_office.yaml
    - !include software/desktop_software/textual.yaml
    - !include software/desktop_software/things.yaml
    - !include software/desktop_software/vmware_fusion.yaml

  Music Production Software / DAWs, Tools & Drivers:
    - !include software/production_software/ableton_live_10_suite.yaml
    # - !include software/production_software/celemony_melodyne_editor.yaml
    - !include software/production_software/elicenser_control_center.yaml
    - !include software/production_software/focusrite_control.yaml
    - !include software/production_software/ilok_license_manager.yaml
    - !include software/production_software/native_instruments_native_access.yaml
    - !include software/production_software/novation_remote_sl_template_editor.yaml
    - !include software/production_software/musescore.yaml
    - !include software/production_software/ocenaudio.yaml
    - !include software/production_software/steinberg_cubase_pro_9v5.yaml
    - !include software/production_software/touchosc_editor.yaml

  Music Production Software / Plug-ins (Effect):
    # ArtsAcoustic
    - !include software/production_plugin_effects/artsacoustic_reverb.yaml

    # Audeze
    - !include software/production_plugin_effects/audeze_reveal.yaml

    # Audio Damage
    # - !include software/production_plugin_effects/audio_damage_eos.yaml

    # Cableguys
    # - !include software/production_plugin_effects/cableguys_filtershaper.yaml
    - !include software/production_plugin_effects/cableguys_shaperbox.yaml
    - !include software/production_plugin_effects/cableguys_volumeshaper.yaml

    # Cytomic
    - !include software/production_plugin_effects/cytomic_the_drop.yaml
    - !include software/production_plugin_effects/cytomic_the_glue.yaml

    # Dada Life
    # - !include software/production_plugin_effects/dada_life_sausage_fattener.yaml

    # DMG Audio
    # - !include software/production_plugin_effects/dmgaudio_compassion.yaml
    - !include software/production_plugin_effects/dmgaudio_dualism.yaml
    # - !include software/production_plugin_effects/dmgaudio_equality.yaml
    # - !include software/production_plugin_effects/dmgaudio_equick.yaml
    - !include software/production_plugin_effects/dmgaudio_equilibrium.yaml
    - !include software/production_plugin_effects/dmgaudio_essence.yaml
    - !include software/production_plugin_effects/dmgaudio_expurgate.yaml
    - !include software/production_plugin_effects/dmgaudio_limitless.yaml
    # - !include software/production_plugin_effects/dmgaudio_pitchfunk.yaml
    - !include software/production_plugin_effects/dmgaudio_trackcomp.yaml
    - !include software/production_plugin_effects/dmgaudio_trackcontrol.yaml
    - !include software/production_plugin_effects/dmgaudio_trackds.yaml
    - !include software/production_plugin_effects/dmgaudio_trackgate.yaml
    - !include software/production_plugin_effects/dmgaudio_tracklimit.yaml
    - !include software/production_plugin_effects/dmgaudio_trackmeter.yaml

    # Eventide
    # - !include software/production_plugin_effects/eventide_2016_stereo_room.yaml

    # Exponential Audio
    - !include software/production_plugin_effects/exponential_audio_r2_stereo_reverb.yaml

    # Focusrite
    # - !include software/production_plugin_effects/focusrite_red_plugin_suite.yaml

    # Goodhertz
    # - !include software/production_plugin_effects/goodhertz_canopener_studio.yaml

    # Illformed
    # BUGGY: Illformed Glitch crashes frequently when being inserted in Cubase
    # - !include software/production_plugin_effects/illformed_glitch.yaml

    # Klanghelm
    - !include software/production_plugin_effects/klanghelm_vumt.yaml

    # Native Instruments
    # - !include software/production_plugin_effects/native_instruments_driver.yaml
    - !include software/production_plugin_effects/native_instruments_phasis.yaml
    # - !include software/production_plugin_effects/native_instruments_premium_tube_series.yaml
    - !include software/production_plugin_effects/native_instruments_replika_xt.yaml
    # - !include software/production_plugin_effects/native_instruments_reverb_classics.yaml
    # - !include software/production_plugin_effects/native_instruments_solid_mix_series.yaml
    - !include software/production_plugin_effects/native_instruments_supercharger_gt.yaml
    - !include software/production_plugin_effects/native_instruments_transient_master.yaml
    - !include software/production_plugin_effects/native_instruments_vintage_compressors.yaml

    # Relab
    - !include software/production_plugin_effects/relab_lx480_complete.yaml

    # Softube
    # - !include software/production_plugin_effects/softube_amp_room_essentials.yaml
    # - !include software/production_plugin_effects/softube_drawmer_s73.yaml
    # - !include software/production_plugin_effects/softube_fet_compressor.yaml
    # - !include software/production_plugin_effects/softube_fix_flanger_and_doubler.yaml
    # - !include software/production_plugin_effects/softube_saturation_knob.yaml
    # - !include software/production_plugin_effects/softube_tsar_1r.yaml
    # - !include software/production_plugin_effects/softube_tube_delay.yaml

    # Sonalksis
    - !include software/production_plugin_effects/sonalksis_plugin_manager.yaml
    - !include software/production_plugin_effects/sonalksis_creative_elements.yaml
    # - !include software/production_plugin_effects/sonalksis_essentials.yaml
    # - !include software/production_plugin_effects/sonalksis_freeg.yaml
    # - !include software/production_plugin_effects/sonalksis_mastering_suite.yaml
    # - !include software/production_plugin_effects/sonalksis_multiband_dynamics.yaml

    # Soundtoys
    # BUGGY: Soundtoys plugins crash randomly when being inserted in Cubase
    # - !include software/production_plugin_effects/soundtoys_echoboy_jr.yaml
    # - !include software/production_plugin_effects/soundtoys_little_plate.yaml
    # - !include software/production_plugin_effects/soundtoys_sie_q.yaml

    # u-he
    # BUGGY: u-he plugins crash Cubase randomly due to a bug with the preset browser
    # - !include software/production_plugin_effects/u_he_mfm2.yaml
    # - !include software/production_plugin_effects/u_he_satin.yaml
    # - !include software/production_plugin_effects/u_he_uhbik.yaml

    # ValhallaDSP
    # - !include software/production_plugin_effects/valhalladsp_valhallaspacemodulator.yaml
    # BUGGY: ValhallaVintageVerb crashes Cubase randomly when using multiple instances and popups
    # - !include software/production_plugin_effects/valhalladsp_valhallavintageverb.yaml

    # Voxengo
    # - !include software/production_plugin_effects/voxengo_deft_compressor.yaml
    - !include software/production_plugin_effects/voxengo_elephant.yaml
    # - !include software/production_plugin_effects/voxengo_glisseq.yaml
    # - !include software/production_plugin_effects/voxengo_msed.yaml
    # - !include software/production_plugin_effects/voxengo_span.yaml
    # - !include software/production_plugin_effects/voxengo_voxformer.yaml

  # Music Production Software / Plug-ins (Guitar Rig Effects):
  #   - !include software/production_plugin_effects/native_instruments_guitar_rig_5.yaml
  #   - !include software/production_plugin_effects/native_instruments_guitar_rig_effects/native_instruments_rammfire.yaml
  #   - !include software/production_plugin_effects/native_instruments_guitar_rig_effects/native_instruments_reflektor.yaml
  #   - !include software/production_plugin_effects/native_instruments_guitar_rig_effects/native_instruments_traktors_12.yaml

  Music Production Software / Plug-ins (Instrument):
    # LennarDigital
    - !include software/production_plugin_instruments/lennardigital_sylenth1.yaml

    # Modartt
    - !include software/production_plugin_instruments/modartt_pianoteq.yaml

    # Native Instruments
    # - !include software/production_plugin_instruments/native_instruments_absynth_5.yaml
    - !include software/production_plugin_instruments/native_instruments_battery_4.yaml
    # - !include software/production_plugin_instruments/native_instruments_fm8.yaml
    # - !include software/production_plugin_instruments/native_instruments_komplete_kontrol.yaml
    - !include software/production_plugin_instruments/native_instruments_kontakt_5.yaml
    - !include software/production_plugin_instruments/native_instruments_massive.yaml

    # Reveal Sound
    - !include software/production_plugin_instruments/reveal_sound_spire.yaml

    # Spectrasonics
    - !include software/production_plugin_instruments/spectrasonics_omnisphere.yaml

    # Steinberg
    # - !include software/production_plugin_instruments/steinberg_padshop.yaml
    # - !include software/production_plugin_instruments/steinberg_retrologue.yaml

    # Synapse Audio
    - !include software/production_plugin_instruments/synapse_audio_dune.yaml

    # u-he
    # BUGGY: u-he plugins crash Cubase randomly due to a bug with the preset browser
    # - !include software/production_plugin_instruments/u_he_hive.yaml
    # - !include software/production_plugin_instruments/u_he_zebra.yaml

    # Xfer Records
    - !include software/production_plugin_instruments/xfer_records_serum.yaml

  # Music Production Software / Plug-ins (Reaktor Instruments & Effects):
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_6.yaml
  #   # Reaktor Effects
  #   - !include software/production_plugin_effects/native_instruments_reaktor_effects/native_instruments_molekular.yaml
  #   - !include software/production_plugin_effects/native_instruments_reaktor_effects/native_instruments_the_finger.yaml
  #   - !include software/production_plugin_effects/native_instruments_reaktor_effects/native_instruments_the_mouth.yaml
  #   # Reaktor Instruments
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_flesh.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_form.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_kontour.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_monark.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_polyplex.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_razor.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_reaktor_prism.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_reaktor_spark.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_rounds.yaml
  #   - !include software/production_plugin_instruments/native_instruments_reaktor_instruments/native_instruments_skanner_xt.yaml

dock_layout: !include software/dock_layout.yaml
launchpad_layout: !include software/launchpad_layout.yaml
