# Specify files or folders which are to be copied
software_app_files:

  # ---------------------------------------------------------------------------
  # General Software
  # ---------------------------------------------------------------------------

  # 1Password
  - source: !join_path [*app_license_dir, General/1Password/License.onepassword-license]
    path: ~/Library/Group Containers/2BUA8C4S2C.com.agilebits/License/License.onepassword-license

  # DaisyDisk
  - source: !join_path [*app_license_dir, General/DaisyDisk/License.DaisyDisk]
    path: ~/Library/Application Support/DaisyDisk/License.DaisyDisk

  # Dash
  - source: !join_path [*app_license_dir, General/Dash/license.dash-license]
    path: ~/Library/Application Support/Dash/License/license.dash-license

  # Entropy
  - source: !join_path [*app_license_dir, General/Entropy/.els-A4AD28617A455C07768787313A53E2F79D9FA258]
    path: ~/Library/Application Support/.els-A4AD28617A455C07768787313A53E2F79D9FA258

  # Focus
  - source: !join_path [*app_license_dir, General/Focus/.491062.padl]
    path: ~/.491062.padl
  - source: !join_path [*app_license_dir, General/Focus/paddata.padl]
    path: ~/Library/Application Support/Focus/paddata.padl

  # Spotify
  - source: files/spotify/watch-sources.bnk
    path: ~/Library/Application Support/Spotify/Users/fgimian-user/watch-sources.bnk

  # Sublime Text
  - source: !join_path [*app_license_dir, General/Sublime Text/License.sublime_license]
    path: ~/Library/Application Support/Sublime Text 3/Local/License.sublime_license
  - source: !join_path [*app_license_dir, General/Sublime Text/Doxy.sublime-license]
    path: ~/Library/Application Support/Sublime Text 3/Packages/User/Doxy.sublime-license

  # Textual
  - source: !join_path [*app_license_dir, General/Textual/Textual_User_License.plist]
    path: ~/Library/Application Support/Textual/Textual_User_License.plist

  # VMware Fusion
  - source: files/vmware_fusion/preferences
    path: ~/Library/Preferences/VMware Fusion/preferences
  - source: !join_path [*app_license_dir, General/VMware Fusion/license-fusion-80-e1-201505]
    path: /Library/Preferences/VMware Fusion/license-fusion-80-e1-201505
    sudo: yes

  # ---------------------------------------------------------------------------
  # Music Production Software
  # ---------------------------------------------------------------------------

  # Ableton Live 9 Suite
  - source: !join_path [*app_license_dir, Music Production/Ableton/Ableton Live 9 Suite/Unlock.cfg]
    path: ~/Library/Application Support/Ableton/Live 9.7/Unlock/Unlock.cfg

  # ArtsAcoustic Reverb
  - source: !join_path [*app_license_dir, Music Production/ArtsAcoustic/ArtsAcoustic Reverb/Preference.xml]
    path: ~/Library/Application Support/ArtsAcoustic/Reverb/Preference.xml

  # Cableguys FilterShaper
  - source: !join_path [*app_license_dir, Music Production/Cableguys/Cableguys FilterShaper/de.cableguys.filtershaper3.plist]
    path: ~/Library/Preferences/de.cableguys.filtershaper3.plist

  # Cableguys VolumeShaper
  - source: !join_path [*app_license_dir, Music Production/Cableguys/Cableguys VolumeShaper/de.cableguys.volumeshaper4.plist]
    path: ~/Library/Preferences/de.cableguys.volumeshaper4.plist

  # Celemony Melodyne Editor
  - source: !join_path [*app_license_dir, Music Production/Celemony/Celemony Melodyne Editor/Melodyne singletrack.license]
    path: /Library/Application Support/Celemony/Licenses/Melodyne singletrack.license
    sudo: yes

  # DMG Audio Compassion
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Compassion/license]
    path: ~/Library/Application Support/DMGAudio/Compassion/license

  # DMG Audio Dualism
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Dualism/license]
    path: ~/Library/Application Support/DMGAudio/Dualism/license

  # DMG Audio EQuilibrium
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio EQuilibrium/license]
    path: ~/Library/Application Support/DMGAudio/EQuilibrium/license

  # DMG Audio Essence
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Essence/license]
    path: ~/Library/Application Support/DMGAudio/Essence/license

  # DMG Audio Expurgate
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Expurgate/license]
    path: ~/Library/Application Support/DMGAudio/Expurgate/license

  # DMG Audio Limitless
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio Limitless/license]
    path: ~/Library/Application Support/DMGAudio/Limitless/license

  # DMG Audio PitchFunk
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio PitchFunk/license]
    path: ~/Library/Application Support/DMGAudio/PitchFunk/license

  # DMG Audio TrackControl
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackControl/license]
    path: ~/Library/Application Support/DMGAudio/TrackControl/license

  # DMG Audio TrackDS
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackDS/license]
    path: ~/Library/Application Support/DMGAudio/TrackDS/license

  # DMG Audio TrackGate
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackGate/license]
    path: ~/Library/Application Support/DMGAudio/TrackGate/license

  # DMG Audio TrackLimit
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackLimit/license]
    path: ~/Library/Application Support/DMGAudio/TrackLimit/license

  # DMG Audio TrackMeter
  - source: !join_path [*app_license_dir, Music Production/DMGAudio/DMGAudio TrackMeter/license]
    path: ~/Library/Application Support/DMGAudio/TrackMeter/license

  # Focusrite Control
  - source: files/focusrite_control/Focusrite Control.settings
    path: ~/Library/Application Support/Focusrite/Focusrite Control/Settings/Focusrite Control.settings

  # Focusrite Red Plugin Suite
  - source: !join_path [*app_license_dir, Music Production/Focusrite/Focusrite Red Plugin Suite/Red2Red3Plugin.txt]
    path: ~/Music/Focusrite/Activation/Red2Red3Plugin.txt

  # Goodhertz CanOpener
  - source: !join_path [*app_license_dir, Music Production/Goodhertz/Goodhertz CanOpener Studio/Interface.interface]
    path: ~/Music/.GDHZ/Interface.interface

  # Relab LX480 Complete
  - source: files/relab_lx480_complete/Preferences.xml
    path: /Library/Application Support/Relab Development/LX480 Complete/Preferences.xml

  # Reveal Sound Spire
  - source: !join_path [*app_license_dir, Music Production/Reveal Sound/Reveal Sound Spire/spire.lic]
    path: ~/Library/Application Support/RevealSound/spire.lic

  # Spectrasonics Omnisphere
  - source: !join_path [*app_license_dir, Music Production/Spectrasonics/Spectrasonics Omnisphere/net.spectrasonics.V6.plist]
    path: ~/Library/Preferences/net.spectrasonics.V6.plist

  # Studio Devil Amp Modeler Pro
  - source: !join_path [*app_license_dir, Music Production/Studio Devil/Studio Devil Amp Modeler Pro/com.studiodevil.amp.plist]
    path: ~/Library/Preferences/com.studiodevil.amp.plist

  # Synapse Audio DUNE
  - source: !join_path [*app_license_dir, Music Production/Synapse Audio/Synapse Audio DUNE/.DUNE2reg]
    path: /Library/Application Support/Synapse Audio/.DUNE2reg
    sudo: yes

  # u-he Hive
  - source: !join_path [*app_license_dir, Music Production/u-he/u-he Hive/com.u-he.Hive.plist]
    path: ~/Library/Application Support/u-he/com.u-he.Hive.plist

  # u-he MFM2
  - source: !join_path [*app_license_dir, Music Production/u-he/u-he MFM2/com.u-he.MFM2.plist]
    path: ~/Library/Application Support/u-he/com.u-he.MFM2.plist

  # u-he Satin
  - source: !join_path [*app_license_dir, Music Production/u-he/u-he Satin/com.u-he.Satin.plist]
    path: ~/Library/Application Support/u-he/com.u-he.Satin.plist

  # u-he Uhbik
  - source: !join_path [*app_license_dir, Music Production/u-he/u-he Uhbik/com.u-he.Uhbik.plist]
    path: ~/Library/Application Support/u-he/com.u-he.Uhbik.plist

  # u-he Zebra
  - source: !join_path [*app_license_dir, Music Production/u-he/u-he Zebra/com.u-he.Zebra2.plist]
    path: ~/Library/Application Support/u-he/com.u-he.Zebra2.plist

  # ValhallaDSP ValhallaVintageVerb
  - source: !join_path [*app_license_dir, Music Production/ValhallaDSP/ValhallaDSP ValhallaVintageVerb/ValhallaVintageVerb.settings]
    path: ~/Library/Preferences/ValhallaVintageVerb.settings

  # Voxengo Deft Compressor
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Deft Compressor/product-key-name]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Deft Compressor/product-key-name
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Deft Compressor/product-key-value]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Deft Compressor/product-key-value

  # Voxengo Elephant
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Elephant/product-key-name]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Elephant/product-key-name
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Elephant/product-key-value]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Elephant/product-key-value

  # Voxengo GlissEQ
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo GlissEQ/product-key-name]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/GlissEQ/product-key-name
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo GlissEQ/product-key-value]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/GlissEQ/product-key-value

  # Voxengo Voxformer
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Voxformer/product-key-name]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Voxformer/product-key-name
  - source: !join_path [*app_license_dir, Music Production/Voxengo/Voxengo Voxformer/product-key-value]
    path: ~/Library/Preferences/Voxengo/Audio Plug-Ins/Voxformer/product-key-value

  # Xfer Records Serum
  - source: !join_path [*app_license_dir, Music Production/Xfer Records/Xfer Records Serum/user.dat]
    path: ~/Library/Application Support/com.xferrecords.serum/user.dat

  # ---------------------------------------------------------------------------
  # Dotfiles
  # ---------------------------------------------------------------------------

  # Bash Profile
  - source: files/dotfiles/.bash_profile
    path: ~/.bash_profile

  # Git Configuration
  - source: files/dotfiles/.gitconfig
    path: ~/.gitconfig

  # SSH Configuration (Sierra specific)
  # - source: files/dotfiles/.ssh/config
  #   path: ~/.ssh/config

  # Fish Profile
  - source: files/dotfiles/.config/fish/config.fish
    path: ~/.config/fish/config.fish

  # IPython Configuration
  - source: files/dotfiles/.ipython/profile_default/ipython_config.py
    path: ~/.ipython/profile_default/ipython_config.py
