# Specify files which are to be symlinked to others
software_app_symlinks:
  # Git cdiff
  - source: /usr/local/bin/cdiff
    path: /usr/local/bin/git-cdiff

  # Audio Hijack
  - source: !join_path [*app_config_dir, Audio Hijack]
    path: '~/Library/Application Support/Audio Hijack'

  # OpenEmu
  - source: !join_path [*app_config_dir, OpenEmu/BIOS]
    path: '~/Library/Application Support/OpenEmu/BIOS'
  - source: !join_path [*app_config_dir, OpenEmu/Bindings]
    path: '~/Library/Application Support/OpenEmu/Bindings'
  - source: !join_path [*app_config_dir, OpenEmu/Cores]
    path: '~/Library/Application Support/OpenEmu/Cores'
  - source: !join_path [*app_config_dir, OpenEmu/Game Library]
    path: '~/Library/Application Support/OpenEmu/Game Library'
  - source: !join_path [*app_config_dir, OpenEmu/Save States]
    path: '~/Library/Application Support/OpenEmu/Save States'

  # Cubase
  - source: ~/Music/Presets
    path: ~/Library/Audio/Presets
