# Specify files which are to be symlinked to others
software_app_symlinks:
  # Git cdiff
  - src: /usr/local/bin/cdiff
    dest: /usr/local/bin/git-cdiff

  # Audio Hijack
  - src: !join_path [*app_config_dir, Audio Hijack]
    dest: '~/Library/Application Support/Audio Hijack'

  # OpenEmu
  - src: !join_path [*app_config_dir, OpenEmu/BIOS]
    dest: '~/Library/Application Support/OpenEmu/BIOS'
  - src: !join_path [*app_config_dir, OpenEmu/Bindings]
    dest: '~/Library/Application Support/OpenEmu/Bindings'
  - src: !join_path [*app_config_dir, OpenEmu/Cores]
    dest: '~/Library/Application Support/OpenEmu/Cores'
  - src: !join_path [*app_config_dir, OpenEmu/Game Library]
    dest: '~/Library/Application Support/OpenEmu/Game Library'
  - src: !join_path [*app_config_dir, OpenEmu/Save States]
    dest: '~/Library/Application Support/OpenEmu/Save States'

  # Cubase
  - src: ~/Music/Presets
    dest: ~/Library/Audio/Presets
