_: &dock_layout
  # Dock applications (in the left section)
  apps:
    - ForkLift
    - Siri
    - Launchpad
    - Safari
    - Sublime Text
    - Utilities/Terminal
    - Cubase 9.5
    - MuseScore 2
    - XLD
    - Focusrite Control
    - Spotify
    - OpenEmu
    - Messages
    - Skype
    - Slack
    - Textual
    - Clear
    - VMware Fusion
    - App Store
    - System Preferences

  # Dock folders and URLs (in the right section)
  other:
    - path: ~/Downloads
