---
# Dock applications (in the left section)
apps:
  - Launchpad
  - Safari
  - Sublime Text
  - Visual Studio Code
  - Utilities/Terminal
  - Cubase 9.5
  - XLD
  - Focusrite Control
  - Spotify
  - OpenEmu
  - Messages
  - Skype
  - Things3
  - VMware Fusion
  - App Store
  - System Preferences

# Dock folders and URLs (in the right section)
other:
  - path: ~/Downloads
