_: &ableton_live_9_suite
  name: Ableton Live 9 Suite
  cask: ableton-live-9-suite
  file:
    # License
    - path: ~/Library/Application Support/Ableton
      state: directory
    - path: ~/Library/Application Support/Ableton/Live 9.7
      state: directory
    - path: ~/Library/Application Support/Ableton/Live 9.7/Unlock
      state: directory
    - path: ~/Library/Application Support/Ableton/Live 9.7/Unlock/Unlock.cfg
      source: !join_path [*app_license_dir, Music Production/Ableton/Ableton Live 9 Suite/Unlock.cfg]
