_: &elicenser_control_center
  name: eLicenser Control Center
  plist:
    - domain: com.Syncrosoft.LCC
      values:
        Show_LCC_Welcome_on_LCC_Launch: false
        Show_Maintenance_on_LCC_Launch: false
