_: &focusrite_control
  name: Focusrite Control
  cask: focusrite-control
  file:
    - source: files/focusrite_control/Focusrite Control.settings
      path: ~/Library/Application Support/Focusrite/Focusrite Control/Settings/Focusrite Control.settings
