_: &focusrite_control
  name: Focusrite Control
  cask: focusrite-control
  file:
    # Preferences
    - path: ~/Library/Application Support/Focusrite
      state: directory
    - path: ~/Library/Application Support/Focusrite/Focusrite Control
      state: directory
    - path: ~/Library/Application Support/Focusrite/Focusrite Control/Settings
      state: directory
    - path: ~/Library/Application Support/Focusrite/Focusrite Control/Settings/Focusrite Control.settings
      source: files/focusrite_control/Focusrite Control.settings
