_: &steinberg_cubase_pro_9
  name: Steinberg Cubase Pro 9
  cask:
    - steinberg-cubase-pro-9
    - steinberg-cubase-pro-9-update
  symlink:
    # Plug-in Presets
    # TODO Ableton Live doesn't like this at all
    - path: ~/Library/Audio/Presets
      source: ~/Music/Presets
      # TODO mode: '0700'
