_: &native_instruments_vintage_compressors
  name: Native Instruments Vintage Compressors
  cask:
    - native-instruments-vc-160-fx
    - native-instruments-vc-2a-fx
    - native-instruments-vc-76-fx
